### ISSUE TITLE
Regression in onClick for Menu component

### ISSUE THREAD

**Issue by abramobagnara** [ant-design/ant-design#10368]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
any

### Reproduction link
[https://codepen.io/abramo/pen/mLMjVG](https://codepen.io/abramo/pen/mLMjVG)

### Steps to reproduce
Open the codepen link and click on nav 1 menu item

### What is expected?
onClick handler should be called once with menu item info as argument

### What is actually happening?
onClick handler is called twice: the first time with the correct menu item info as argument and a second time with React event

---
The browser console will show the two calls and a failed assertion related to the unexpected call.

**Comment by afc163** [comment]
Your codepen seems to be OK

**Comment by abramobagnara** [comment]
Sorry, I've forgotten to restore the settings after I've tried with antd 3.4.5 to ensure it was a regression.
Please retry now.

**Comment by xVanTuring** [comment]
+1, I just got the same problem

**Comment by xVanTuring** [comment]
i just add
``` js
  if (e.domEvent) {    
    e.domEvent.stopPropagation()
  }
```
to the end of the function.
Problem Solved(Maybe).

**Comment by qiaoyixuan** [comment]
+1

**Comment by yesmeck** [comment]
Should be fixed in `rc-menu@7.0.3`

**Comment by hsz** [comment]
Problem is still valid for `rc-menu@7.0.3` when using `Menu.ItemGroup` wrapper.

**Comment by yesmeck** [comment]
@picodoth

**Comment by picodoth** [comment]
fixed in https://github.com/react-component/menu/commit/9ff201073c17f9e3b132dfeb624d8353cd0717c5

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/menu/commit/1bf0c8dc6dc6134316dd8f4ed433b0544b35330d?

**Comment by picodoth** [comment]
@afc163 是的
