### ISSUE TITLE
controlled Select wont hide Options after click

### ISSUE THREAD

**Issue by CallMeXYZ** [ant-design/ant-design#10400]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
React 16.2 below

### Reproduction link
[https://codepen.io/anon/pen/ZoaKvV?editors=1111](https://codepen.io/anon/pen/ZoaKvV?editors=1111)

### Steps to reproduce
1.set `React` version <=`16.2.0` 
2.set `Antd` version `3.5.0`
3.open the link

### What is expected?
hide options after click any option

### What is actually happening?
1.options menu stays open after click new option
2.options menu closes only after click old option

---
this only happens on `React`<= `16.2.0` & `Antd`=`3.5.0` & controlled select, the change log indicates the update of  `rc-select` dependency , maybe that?

**Comment by daggerjames** [comment]
+1 for same issue

**Comment by yesmeck** [comment]
It should have been fixed now, try reinstall node_modules.

https://codesandbox.io/s/nkjnxw1n50

**Comment by fpsqdb** [comment]
reinstalled, menu will close after click old option, but the new option still have this issue.

**Comment by yesmeck** [comment]
@fpsqdb Could you reproduce it on https://codesandebox.io?

**Comment by CallMeXYZ** [comment]
@yesmeck `React 16.2.0` still has the problem. [see](https://codesandbox.io/s/18p11xnv57).
Do you mean we cannot use `antd 3.5.0` under `React 16.2.0`?

**Comment by CallMeXYZ** [comment]
@wei494989879 why?

**Comment by wei494989879** [comment]
@CallMeXYZ In my way, you have to change the pagination component.But the current version does not have this problem. There is no need to do so.
