### ISSUE TITLE
Table without current prop should respond to user interactions.

### ISSUE THREAD

**Issue by BetaRabbit** [ant-design/ant-design#1433]
If a `Table`'s `pagination` prop does not contain `current` prop, this `Table` should not be regarded as a controlled component.
An `Input` without `value` prop allows user interactions (change value), so should the `Table` without `current` prop. Changing input's value has no differences from changing pagination's current.

## Online Demo
Here comes the online demo. Please try both pagination and input component.
http://codepen.io/BetaRabbit/pen/EKLjom?editors=0110

## Environment Information
- Ant-Design  0.12.14
- Ubuntu 15.10
- Chrome Version 49.0.2623.87 (64-bit)

**Comment by BetaRabbit** [comment]
Propose a PR #1434  :smile:

**Comment by benjycui** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/4835471210b92d6f2755a4058c7c2c10187a7849

**Comment by benjycui** [comment]
Any way, THX!

**Comment by BetaRabbit** [comment]
Awesome, u r moving fast.
Just tried 4835471, unfortunately, the problem is still there.
BTW, have you ever tried `setState` in pagination's `onChange` handler?

```
constructor(props) {
  super(props)

  this.state = {
    current: 1,
  };
}

...

const pagination = {
  total: data.length,
  showSizeChanger: true,
  onShowSizeChange(current, pageSize) {
    console.log('Current: ', current, '; PageSize: ', pageSize);
  },
  onChange: (current) => {
    console.log('Current: ', current);
    this.setState({current});
  }
};

...

return <Table columns={columns} dataSource={data} pagination={pagination} />;
```

**Comment by afc163** [comment]
Thx!

**Comment by BetaRabbit** [comment]
Great! Thanks!! :+1:
