### ISSUE TITLE
[Table Pagination Bug] when PageSize is larger than current data length, <Table /> will always show the first page data.

### ISSUE THREAD

**Issue by sdli** [ant-design/ant-design#14557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/sdli-code/pen/RvrWmM?editors=0010](https://codepen.io/sdli-code/pen/RvrWmM?editors=0010)

### Steps to reproduce
Click first Button, bug will be shown on table , and the table will always show the first page data even if you select the second page. And then click the second button, the bug will disappear.

### What is expected?
If table Data is smaller than Pagesize, data should be shown rightly.

### What is actually happening?
The table will always show the first page data even if you select the second page. 

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.x |
| System | Windows10 |
| Browser | Chrome/ 1.0.3578.98 |

---
I have fixed the line below in Table.tsx, and then problem is resolved.
https://github.com/ant-design/ant-design/blob/f5cbf0f9f18935793a5054c54cdde9da9529c6b5/components/table/Table.tsx#L1016

Change it into below:

getCurrentPageData = function(){
      var data = this.getLocalData();
      var current;
      var pageSize;
      var state = this.state; // 如果没有分页的话，默认全部展示

      if (!this.hasPagination()) {
        pageSize = Number.MAX_VALUE;
        current = 1;
      } else {
        pageSize = state.pagination.pageSize;
        current = this.getMaxCurrent(state.pagination.total || data.length);
      } // 分页
      // ---
      // 当数据量少于等于每页数量时，直接设置数据
      // 否则进行读取分页数据

      // 【修复】增加current*pageSize的判断
      if (data.length > pageSize || pageSize === Number.MAX_VALUE  || current*pageSize > data.length) {
        data = data.filter(function (_, i) {
          return i >= (current - 1) * pageSize && i < current * pageSize;
        });
      }

      return data;
    }

**Comment by ztplz** [comment]
@th-ko  It has been fixed via https://github.com/ant-design/ant-design/pull/14724, the next release at weekend.

**Comment by damiangreen** [comment]
This still appears to be an issue in the latest version

**Comment by jyfernandez** [comment]
> This still appears to be an issue in the latest version

I agree still experiencing the same warning as of the moment.

**Comment by dubrova-ta-ma** [comment]
Still reproducible issue

**Comment by CesarDav** [comment]
the problem still persists

**Comment by xgqfrms** [comment]
👀

**Comment by XiaoPan-Struggle** [comment]
👀

**Comment by chufall** [comment]
[antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`. Please make sure your config correct data with async mode. 
At version 4.15.0， there's the same bug!

**Comment by Bulala-liu** [comment]
> [antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`. Please make sure your config correct data with async mode.
> At version 4.15.0， there's the same bug!

I also fund it.

**Comment by twoheartliu** [comment]
v4.16.1 same problem

**Comment by Nziranziza** [comment]
I also have this issue

**Comment by Nziranziza** [comment]
When working with restful api, the totalSize is always greater or equal to dataSource length
Let's say your REST api is configured to fetch 10 items per page and you have 100 records in your database
If you request the first, it will respond with something like this `{ page: 1, data: [10 items here...], totalSize: 100 }`;
Such data is enough for you to render Antd design table
```
<Table
current={page}
totalSize={totalSize} // 100 as from API
dataSource={data} // 10 items from the API
/>
```
The pagination looks like this:
![download](https://user-images.githubusercontent.com/37615728/130031071-c14bd639-1f74-4141-8506-42ac6d26abde.png)

If you request the page 32, it will fetch another batch 10 items, our dataSource will have 20 items which still less that totalSize. And as a result page 32 will not show.

**Comment by nagaraj-a** [comment]
I had set the **pageSize** to current page size and that solved the issue for me...

**Comment by syssam** [comment]
face the same issue.
version: 4.16.13

**Comment by DjVreditel** [comment]
> face the same issue. version: 4.16.13

+

**Comment by adhityasan** [comment]
i fix it by passing the pagination object which is including updated `pageSize` in pagination props 
![image](https://user-images.githubusercontent.com/45331931/141770657-3b509b4c-4681-4a75-9553-228c8d093296.png)

**Comment by SilentFlute** [comment]
贴一个我自己的解决方法供大家参考: #https://github.com/ant-design/pro-components/issues/3436#issuecomment-984439793

**Comment by rxomidov** [comment]
Same issue on version: 4.15.4

**Comment by abhisaha1** [comment]
Works for me if I set `hideOnSinglePage` to `true`.

```js
<Table
  ...
  pagination={{
    hideOnSinglePage: true, // <--------- add this
    total: totalCount, 
  }}
/>;
```

**Comment by 2diegoduque** [comment]
Same issue on version: 4.22.3

**Comment by dubrova-ta-ma** [comment]
same issue on version 5.1.5

**Comment by vaynevayne** [comment]
same issue on version 5.11.0
@afc163

**Comment by incodenet** [comment]
same issue on version 5.13.3

**Comment by FishManHell** [comment]
same issue on version 5.18.0

**Comment by robertocerdasilva** [comment]
Same problem !!! Open this
