### ISSUE TITLE
default time of DatePicker should also sync millisecond

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#16660]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0qbfy)

### Steps to reproduce
pick a time, the console will print the millisecond

### What is expected?
my default time is  `moment("00:00:00.000", "HH:mm:ss.SSS")` so I expect the milli second to be 0

### What is actually happening?
millisecond is a random number

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome 71 |

**Comment by rinick** [comment]
resolved in the above PR @yesmeck

**Comment by mcshaman** [comment]
This does not seem to be resolved. Looking at the code sandbox the milliseconds are still not zero.
