### ISSUE TITLE
Table fixed column get wrong display in antd4.1.0 on macOS , Safari

### ISSUE THREAD

**Issue by sb-lee** [ant-design/ant-design#22773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudingtouhelie-ant-design-demo-v976x)

### Steps to reproduce
please make Antd table with horizon scroll , fixed left columns and no fixed right columns

### What is expected?
The last column of the fixed header looks normal

### What is actually happening?
Table fixed column get wrong display on right side
It happen on table with only horizontal scroll  in Safari
| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | Mac OS latest |
| Browser | safari latest |

**Comment by afc163** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/78008584-65d2c800-7372-11ea-9dcd-5dbd1cdc4be4.png">

What's abnormal in safari? I cannot see any.

**Comment by sb-lee** [comment]
@afc163 
Please see the right side  when scroll is in middle.

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/14502051/78028046-54e97d00-7399-11ea-91ff-a23616c23070.png">

**Comment by sb-lee** [comment]
@afc163 , @zombieJ 
Please see the right side  when horizontal scroll is in middle.

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/14502051/78028046-54e97d00-7399-11ea-91ff-a23616c23070.png">

**Comment by dpyzo0o** [comment]
I have another abnormal display on Safari MacOS as below, using the same reproduction link

![demo](https://user-images.githubusercontent.com/24768249/78093774-8730c400-7405-11ea-9707-586463e752e5.gif)

The fixed columns have some gap between and are not fixed at all.

MacOS: 10.13.6
Safari: 12.1.2

**Comment by dpyzo0o** [comment]
@zombieJ

**Comment by dpyzo0o** [comment]
<img width="1381" alt="Screen Shot 2020-04-01 at 10 50 57" src="https://user-images.githubusercontent.com/24768249/78094268-b98ef100-7406-11ea-9444-4e54804e4bc7.png">

Demo on the official website also has the issue.

**Comment by cnzsb** [comment]
Is someone still working on it now? It's still wrong in 4.1.1.

**Comment by imhxc** [comment]
@cnzsb This issue has been resolved and published in 4.1.1. Try removing "node_modules" and reinstalling.

**Comment by cnzsb** [comment]
@imhxc You can simply check the official website, it's still wrong.
![image](https://user-images.githubusercontent.com/9855853/78738259-fcf7db00-7983-11ea-8877-9fb3df5a63e4.png)

**Comment by yoyo837** [comment]
@cnzsb It's works for me.

![image](https://user-images.githubusercontent.com/6134547/78739454-de471380-7986-11ea-86d1-715ecbfe1c86.png)

**Comment by yoyo837** [comment]
@cnzsb What's your browser and system version?

**Comment by cnzsb** [comment]
@yoyo837 
Safari: Version 12.1.1 (14607.2.6.1.1)
OS: Mojave, Version 10.14.5 (18F132)

**Comment by yoyo837** [comment]
Merge to #22377 for tracing.

**Comment by afc163** [comment]
@imhxc @sb-lee Could you help to check whether https://preview-23161-ant-design.surge.sh/components/table/ works?

**Comment by imhxc** [comment]
@afc163 
没有生效，因为 class 中的 position 被行内样式覆盖了，我之前评论了这条 PR ，但是并没有被采纳。
如果需要的话，我可以提交 PR 来修复此问题。
Not working， because the position in the class was covered by the inline style. I commented on this PR before, but it was not adopted.
If necessary, I can submit a PR to fix this problem.
