### ISSUE TITLE
Scroll in popup container

### ISSUE THREAD

**Issue by Firetuy** [ant-design/ant-design#24064]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://zb2rcq.run.stackblitz.io/](https://zb2rcq.run.stackblitz.io/)

### Steps to reproduce
Try scrolling using mouse or exactly between the menu items.

### What is expected?
That scroll works properly

### What is actually happening?
Scroll doesnt work

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | Windows 7 |
| Browser | Chrome |

**Comment by afc163** [comment]
Your stackblitz cannot open and I can't see the source code.

**Comment by Firetuy** [comment]
https://codesandbox.io/s/top-navigation-ant-design-demo-0klnu

Sorry

**Comment by ildarnm** [comment]
@Firetuy, looks like a problem in the key prop. Please, try to set a unique values.
Fixed version [https://codesandbox.io/s/top-navigation-ant-design-demo-f9kw3](https://codesandbox.io/s/top-navigation-ant-design-demo-f9kw3)

**Comment by Firetuy** [comment]
@ildarnm Thanks for the help, but the bug remain, scroll doesnt work properly, only when mouse is in one of the itens
