### ISSUE TITLE
Input.Search onChange event fires with duplicated value when wrapped in AutoComplete and using copy/paste

### ISSUE THREAD

**Issue by rvinzent** [ant-design/ant-design#25102]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-xd80r?file=/index.js)

### Steps to reproduce
- copy/paste any value into the search box in the reproduction link

### What is expected?
If `something` is pasted into the search box, the emitted value should be `something`

### What is actually happening?
pasting (Ctrl   v) `something` into the box emits a value of `somethingsomething`

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | macOS 10.15.4 (19E287) |
| Browser | Chrome Version 83.0.4103.106 (Official Build) (64-bit) |

**Comment by afc163** [comment]
It is likely been fixed in 4.3.5 already: https://codesandbox.io/s/antd-reproduction-template-bfdfz?file=/package.json

**Comment by rvinzent** [comment]
@afc163 I can still reproduce the issue in your reproduction link. I don't think it has been fixed
