### ISSUE TITLE
disabledHours does not work with use12Hours in timepicker

### ISSUE THREAD

**Issue by aslaugsollilja** [ant-design/ant-design#26954]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/AcePool/pen/RwamZyL?editors=0010](https://codepen.io/AcePool/pen/RwamZyL?editors=0010)

### Steps to reproduce
Use `disabledHours` with timepicker that has `use12Hours` enabled. Try to disable hours in the PM, for example, return [1, 2, 15, 16 ]. Only timepicker with 24h format works, and not 12h format.

### What is expected?
You should be able to give the timepicker an array of hours on 24 format and that should map to 12 hour format when using that config.

### What is actually happening?
Both hours in am and pm are disabled, but only from 0-12.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.6 |
| Browser | chrome 85.0.4183.102 |

**Comment by PavelKorchyk** [comment]
up! have the same issue in the v4.8.0
link to reproduce - https://codesandbox.io/s/antd-reproduction-template-forked-76hx3?file=/index.js

**Comment by zombieJ** [comment]
Close since it seems fixed in latest version.

**Comment by umar-epacken** [comment]
this issue is still existing. The picker does not respect 12 hour format disabledHourRange if the meridian value is PM.
