### ISSUE TITLE
scroll is not visible in select component

### ISSUE THREAD

**Issue by talwaserman** [ant-design/ant-design#27152]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zmiou)

### Steps to reproduce
go to your website
https://ant.design/components/select/#header

look at the tags mode example

start writing and you will get options in the select, but you don't see the scroll. 
this is an issue since you don't know that you have more values other then what is visible
only when you scroll the options the scroll appears.

i also checked on safari, and you also can't see the scroll only when you start scrolling

### What is expected?
expecting to see scroll on the right when there are more options then can fit in the dropdown window

### What is actually happening?
currently the scroll appear only when you scroll the options in the dropdown

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | react-16.9.0 |
| System | mac,windows |
| Browser | Chrome Version 86.0.4240.75 |

**Comment by jasonejavier** [comment]
I am also experiencing the same behavior. Maybe because of the virtual list.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/pull/557

**Comment by funkpotamus-prime** [comment]
I am still seeing this behavior in tags mode. It is reproducible [here](https://ant.design/components/select/#components-select-demo-multiple). Just click on one item in the drop down list, wait about 1/2 second and then the scroll bar disappears.

**Comment by molokovev** [comment]
@funkpotamus-prime 
> I am still seeing this behavior in tags mode. It is reproducible [here](https://ant.design/components/select/#components-select-demo-multiple). Just click on one item in the drop down list, wait about 1/2 second and then the scroll bar disappears.

I've been struggled with the same issue.. First, I had to set the `virtual` prop to false for Select (virtual-list [has a custom scrollbar](https://github.com/react-component/virtual-list/blob/master/src/List.tsx#L342) with this non-customizable [hiding logic](https://github.com/react-component/virtual-list/blob/a107a64c8cda4aee69aa3447ad8e77f5bd4085de/src/ScrollBar.tsx#L61)). Though I was lucky for not needing the virtual logic in my case.
And then it turned out to be the modern browser's native behaviour — to hide the scrollbars as well. You can disable it with `::-webkit-scrollbar` and `::-webkit-scrollbar-thumb`.
Like this, for example:
```
::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 10px;
}
::-webkit-scrollbar-thumb {
  border-radius: 5px;
  background-color: rgba(0,0,0,.3);
  -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
}
```

**Comment by manjunathadg** [comment]
Hi @molokovev 
I am facing the same scroll issue, I tried to apply the css fix you have suggested, but not sure to which class I need to add the ::-webkit-scrollbar and ::-webkit-scrollbar-thumb. I applied on ant-select-dropdown, it didn't work.
Can you please let me know same.

**Comment by molokovev** [comment]
> Hi @molokovev
> I am facing the same scroll issue, I tried to apply the css fix you have suggested, but not sure to which class I need to add the ::-webkit-scrollbar and ::-webkit-scrollbar-thumb. I applied on ant-select-dropdown, it didn't work.
> Can you please let me know same.

Right, because the scrollbar is shown for `.rc-virtual-list-holder`.
You can get the behaviour you need either using nested selector like `.ant-select-dropdown ::-webkit-scrollbar....` or directly targeting the block like `.rc-virtual-list-holder::-webkit-scrollbar....`

**Comment by josh231101** [comment]
Is this even fixed? Why it's closed?||

**Comment by sylvainpe** [comment]
I still have this problem with latest antd version

**Comment by josh231101** [comment]
Hi @sylvainpe check this https://ant.design/components/select/#API scroll down to FAQ. 

Why sometime customize Option cause scroll break?#
Virtual scroll internal set item height as 32px. You need to adjust listItemHeight when your option height is less and listHeight config list container height:

<Select listItemHeight={10} listHeight={250} />
Note: listItemHeight and listHeight are internal props. Please only modify when necessary.

PROS: This fixes your problems
CONS: In my antd version, scrollbar is not styled

**Comment by shahidsha1612** [comment]
i have found a way to keep the scroll intact ,
u have to give dropdownclassname and use scss and target .rc-virtual-list-scrollbar class .eg:myclassname{
div{
div{}
div{rc-virtual-list-scrollbar{}
}
}
the above example helped to fix and this doesnt affect other dropdowns so u can have what u want.
Hope this helped

**Comment by tleclaire** [comment]
Still seeing this behavior, will that ever be fixed?

**Comment by josh231101** [comment]
> Still seeing this behavior, will that ever be fixed?

Try last 2 comments. Mine and @shahidsha1612

**Comment by tleclaire** [comment]
Unfortunately none of them work...

**Comment by funkpotamus-prime** [comment]
> Unfortunately none of them work...

@tleclaire I just updated to 4.16.13 yesterday and this issue appears to be fixed.

Can someone else verify please?

**Comment by sema4-hennadiipetrov** [comment]
I still have this problem when add getPopupContainer={trigger => trigger.parentNode} as a prop of <Select> component

**Comment by tanmayaBiswalOdiware** [comment]
> i have found a way to keep the scroll intact , u have to give dropdownclassname in the select component eg: "Select dropdownClassName="myclassname" and use scss and target .rc-virtual-list-scrollbar class .eg:myclassname{ div{ div{} div{rc-virtual-list-scrollbar{} } } the above example helped to fix and this doesnt affect other dropdowns so u can have what u want. Hope this helped

While this is not getting solved, I used the quoted comment as an idea and forced the scrollbar to display all the time.

```css
.<className-of-dropdown> .rc-virtual-list .rc-virtual-list-scrollbar {
  display: block!important;
}
```
PS. there is a property under Select component called dropdownClassName that can be used to name the dropdown.

**Comment by wongfunian** [comment]
I noticed that the ant design `select` component is using `rc-virtual-list` to make the virtual list, after doing some research, the CSS style below can make sure the scroll bar is always active even though the cursor not moving for more than 2 or 3 seconds.

```
.rc-virtual-list-scrollbar{
    display: block !important;
}
```

**Comment by vishalkumar124** [comment]
add this line of code in Select Tag
getPopupContainer={trigger => trigger.parentElement}

**Comment by torers-dnv** [comment]
This is still wrong, the scrollbar does not appear at the right time. Can be reproduced on the custom dropdown render example: https://ant.design/components/select#select-demo-custom-dropdown-menu
In the screenshot I have added a ninth item, but no scrollbar appears.
![image](https://github.com/ant-design/ant-design/assets/151788581/fa4d17d1-b98e-45e0-8284-e2f68faad80d)
Scrollbar appears on the eleventh element:
![image](https://github.com/ant-design/ant-design/assets/151788581/46752bdd-0f79-4610-a303-627f14ea7aab)

**Comment by torers-dnv** [comment]
Created new issue https://github.com/ant-design/ant-design/issues/46390

**Comment by hexiaochen666** [comment]
![image](https://github.com/ant-design/ant-design/assets/52769073/95d9e4fa-e524-457b-80e4-b94c17dffd75)
我也存在这个问题，有时候能出现，有时候不能出现，5.9.4的这个版本

**Comment by coder054** [comment]
virtual={false}

**Comment by AzharUddinSheikh** [comment]
`listItemHeight={0}` worked for me
IDK why but I did try few some solution above comment.
