### ISSUE TITLE
Version 4.11.1 significantly increased bundle size

### ISSUE THREAD

**Issue by oceandrama** [ant-design/ant-design#29121]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
Version 4.10.3
![image](https://user-images.githubusercontent.com/23439079/106322718-528cd380-6287-11eb-87d4-34fb10ad6794.png)

Version 4.11.1
![image](https://user-images.githubusercontent.com/23439079/106322797-6c2e1b00-6287-11eb-9f82-45ac6630f6b0.png)

### What is expected?
Bundle size is not increased

### What is actually happening?
 Bundle size is significantly increased

| Environment | Info |
|---|---|
| antd | 4.11.1 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome  87.0.4280.88 |

**Comment by kmocorro** [comment]
Received this warning too. @4.11.2 
<code>You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.</code>

and also the Layout components renders like this:
![image](https://user-images.githubusercontent.com/26828995/106348295-38dba280-6300-11eb-971e-be9854b9e794.png)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/29045

**Comment by gynekolog** [comment]
The issue still exists in the 4.12.2.
I use antd, create-react-app and craco.
I solved warning `You are using a whole package of antd` by replacing `craco-less` with `craco-antd`.

**Comment by afc163** [comment]
@gynekolog Could you provide a reproduce?

**Comment by gynekolog** [comment]
@afc163 There is a clean demo without craco and the issue still exist -> https://codesandbox.io/s/keen-feather-c8dh8?file=/src/App.tsx
or you can check it at any components example like [Button](https://ant.design/components/button/) -> https://codesandbox.io/s/qpk6s?file=/index.js

**Comment by afc163** [comment]
@zombieJ 

- https://unpkg.com/browse/antd@4.11.0/es/index.js
- https://unpkg.com/browse/antd@4.11.1/es/index.js

```
/* @remove-on-es-build-begin */
// this file is not used if use https://github.com/ant-design/babel-plugin-import
var ENV = process.env.NODE_ENV;

if (ENV !== 'production' && ENV !== 'test' && typeof console !== 'undefined' && console.warn && // eslint-disable-line no-console
typeof window !== 'undefined') {
  // eslint-disable-next-line no-console
  console.warn('You are using a whole package of antd, ' + 'please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.');
}
```

These lines is not removed after `4.11.1`.

**Comment by Cyxwmm** [comment]
我也有同样的警告 根据官网的图
![image](https://user-images.githubusercontent.com/22393346/109097028-91645b00-7759-11eb-9296-6ab205cb1de2.png)
antd版本是4.12.3 create-react-app版本是4.0.3 
打包后的体积是进行了tree-shaking的
![image](https://user-images.githubusercontent.com/22393346/109097781-fc626180-775a-11eb-8755-73da787efa02.png)
怎么消除开发环境下的警告？

**Comment by yoyo837** [comment]
Is it a duplicate of #29378?

**Comment by Cyxwmm** [comment]
> Is it a duplicate of #29378?

谢谢回复，是的，他的描述跟我的困惑是一样的

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/29378#issuecomment-782548317
