### ISSUE TITLE
WebSite not work - CDN

### ISSUE THREAD

**Issue by gromov-io** [ant-design/ant-design#29311]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
open site

### What is expected?
polyfill.alicdn.com - fast loaded

### What is actually happening?
CDN - is not responsible https://polyfill.alicdn.com/polyfill.min.js?features=default,es2015,Intl

| Environment | Info |
|---|---|
| antd | undefined |
| React | 0 |
| System | Ubuntu 20.10 |
| Browser | chrome Version 88.0.4324.150 (Official Build) (64-bit) |

---
Country - Russia
![image](https://user-images.githubusercontent.com/46241127/107539531-1be38100-6bd6-11eb-95fd-b2d5e2f4acc5.png)

**Comment by yoyo837** [comment]
Which area are you in? it's working fine here

**Comment by gromov-io** [comment]
> Which area are you in? it's working fine here

```

My IP Host: 185.253.42.22
My IP Location: Russia Federation, Rostov-on-Don, Rostov
Zip Code: 344015
Time Zone: Europe/Moscow
Latitude/Longitude: 47.2361,39.7189

proxy is missing
VPN is missing
```

**Comment by gromov-io** [comment]
Thank you, the problem was solved by itself. CDN started answer 200

**Comment by gromov-io** [comment]
```
ip: "185.253.42.253"
 city: "Moscow"
 region: "Moscow"
 country: "RU"
 loc: "55.7858,37.6256"
 org: "AS204108 Republic Operator of Networks G.O."
 postal: "901001"
 timezone: "Europe/Moscow"
 asn: Object
 asn: "AS204108"
 name: "Republic Operator of Networks G.O."
 domain: "phoenix-dnr.ru"
 route: "185.253.42.0/23"
 type: "isp"
 company: Object
 name: "Republic Operator of Networks G.O."
 domain: "phoenix-dnr.ru"
 type: "isp"
 privacy: Object
 vpn: false
 proxy: false
 tor: false
 hosting: false
 abuse: Object
 address: ""
 country: "RU"
 email: "noc@phoenix-dnr.ru"
 name: "Abuse-C Role"
 network: "185.253.42.0/23"
 phone: ""
 domains: Object
 total: 0
 domains: Array
```

![Снимок экрана от 2021-03-20 22-52-04](https://user-images.githubusercontent.com/46241127/111884059-1f85d700-89d0-11eb-994b-e3d2b6ebecde.png)

**Comment by FoxxMD** [comment]
This is still an issue. Located in USA this request takes a long time to respond and eventually fails.

**Comment by gromov-io** [comment]
@afc163 @yoyo837 
Please re-upload the polyfile to another cdn, it is impossible to wait 3 minutes for the site to load ((((

![image](https://user-images.githubusercontent.com/46241127/117206130-1ecbc780-adfb-11eb-899a-0f5281131f09.png)

**Comment by yoyo837** [comment]
@afc163 Can we manually deploy the site now so they can test it out?
