### ISSUE TITLE
Table header bug when no data and set scroll x and y

### ISSUE THREAD

**Issue by kaioduarte** [ant-design/ant-design#29314]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fixed-header-antd4122-forked-45gbn?file=/index.js)

### Steps to reproduce
- add `scroll={{ x: true, y: true }}` with an empty `dataSource` (header should be broken)
- add an element to the `dataSource` (header should be fine)

### What is expected?
The header should render the same way when we have data (the image below is from v3)
![image](https://user-images.githubusercontent.com/11046907/107561958-16d30180-6bd7-11eb-848a-cda3f4b7a8e6.png)

### What is actually happening?
The header is just rendering the first column, the rest are hidden

![image](https://user-images.githubusercontent.com/11046907/107561738-cfe50c00-6bd6-11eb-97f6-5ca2a7f9db52.png)

| Environment | Info |
|---|---|
| antd | 4.12.3 |
| React | React v17 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by kaioduarte** [comment]
Related to #26701

**Comment by afc163** [comment]
It is a Chrome render bug, works well in Firefox.

<img width="678" alt="图片" src="https://user-images.githubusercontent.com/507615/107779389-3eb19900-6d80-11eb-92f7-5ecb609e0e61.png">

**Comment by kaioduarte** [comment]
Indeed! Thanks, @afc163. Is there any workaround for that?

**Comment by afc163** [comment]
Fixed https://github.com/react-component/table/pull/594

**Comment by kaioduarte** [comment]
@afc163 actually this still an issue :/

https://codesandbox.io/s/antd-reproduction-template-forked-8rj2s?file=/index.js

Kinda related to #30358 

Same table with and without data
![image](https://user-images.githubusercontent.com/11046907/116944622-bf8c7c80-ac6d-11eb-898f-6b1483d9c5ae.png)
