### ISSUE TITLE
Horizontal Menu with one item falls into the collapsed mode

### ISSUE THREAD

**Issue by nicoladelazzari** [ant-design/ant-design#30813]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-36f95?file=/index.js:0-432)

### Steps to reproduce
Create a menu with just one item inside a flexbox container (see Reproduction link)

### What is expected?
The menu item is not collapsed

![Screenshot 2021-06-01 at 17 38 39](https://user-images.githubusercontent.com/57252543/120351498-3a45c780-c300-11eb-9f43-8ce80ac17f1b.png)

### What is actually happening?
The menu item is collapsed

![Screenshot 2021-06-01 at 17 37 36](https://user-images.githubusercontent.com/57252543/120351404-28642480-c300-11eb-8933-27851c0bac11.png)

| Environment | Info |
|---|---|
| antd | 4.16.1 |
| React | 16.14.0 |
| System | macOS 10.15.7 |
| Browser | Firefox 88.0.1 (64-bit), chrome Version 90.0.4430.212 (Official Build) (x86_64) |

---
The container has display: flex

**Comment by AhmedBHameed** [comment]
Yup, I also confirm this issue.
Thanks @nicoladelazzari

**Comment by zombieJ** [comment]
Fixed the init render logic. But it better to set Menu style `flex: auto` to avoid resize window make flex change the menu to narrow width which will not take back.

**Comment by nicoladelazzari** [comment]
Thank you @zombieJ 
Q: Is this included in 4.16.2?
https://github.com/ant-design/ant-design/releases/tag/4.16.2

**Comment by isumix** [comment]
The issue still there in 4.20, though it appears to be only if used with deprecated `Menu.Item`. However if I use the new `items` it will not collapse at all :facepalm:, even if the container gets smaller.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/36604
