### ISSUE TITLE
The whole app freezes whenever dropdown menu is clicked

### ISSUE THREAD

**Issue by mounis-bhat** [ant-design/ant-design#35155]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7gmw9e?file=/index.js)

### Steps to reproduce

Click on dropdown component and the UI will freeze

### What is expected?

On clicking the dropdown menu is supposed to be rendered 

### What is actually happening?

The whole app is freezing

| Environment | Info |
| --- | --- |
| antd | 4.19.5 |
| React | 18 |
| System | Windows 10 |
| Browser | Edge Version 100.0.1185.44 (Chromium) |

---
While going through other issues I found out that react concurrent mode is responsible for UI freezes in various components, and I have checked that this issue disappears for React 17.0.2. So I guess this issue happens because React 18 supports concurrent rendering out of the box.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-x7l5wj?file=/index.js

Fixed in 4.20.0-alpha.1

**Comment by julianklumpers** [comment]
This issue still occurs when using the dropdown of date picker.

**Comment by davitp** [comment]
Can reproduce on collapsing sider menu with 4.21.3

**Comment by davitp** [comment]
@afc163 
Is there any chance this will be fixed soon? Happens in Dropdowns, Popovers and Sider's collapse.

**Comment by popmanhe** [comment]
Why this issue is closed. I still have this issue on antd version:4.21.6.

After reverse to react 17, it's ok.

**Comment by popmanhe** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-x7l5wj?file=/index.js
> 
> Fixed in 4.20.0-alpha.1

The issue still exists in 4.21.6. It's not fixed.

**Comment by SamiAltuncu** [comment]
The issue still exists in 4.21.7. It's not fixed.

**Comment by jaxxreal** [comment]
Why is it marked as closed? I've got exactly the same issues - react@18 + ant@4.21.7

**Comment by dica-xyz** [comment]
It's fixed in 4.22.0. Upgrade to the latest version.

**Comment by tugceK** [comment]
I have got the same issue too  - react@18 + ant@4.15.4

**Comment by jordymeow** [comment]
Same here issue here, with React 18 and Ant 4.15.

**Comment by talha5389** [comment]
Also occuring for me. It even produces if I just render only single `antd` select in isolation

```
  <Select
            size="middle"
            value={null}
            placeholder="Bulk action"
            onChange={(e) => {
                console.log("e", e);
            }}
            allowClear={true}
            disabled={false}
        >
            <Select.Option value={"1"}>Active users</Select.Option>
            <Select.Option value={"2"}>Disable users</Select.Option>
        </Select>
```

Performance profile

![image](https://user-images.githubusercontent.com/14093306/197634145-b039b32f-3931-41f1-8f17-f0c3d85092fa.png)
![image](https://user-images.githubusercontent.com/14093306/197634204-0e7a9964-8338-41ef-bce3-8a5a41677f00.png)


- react@18.2.0
- react-dom@18.2.0
- react-scripts@5.0.1
- antd@4.23.6
- chrome Version 106.0.5249.119

**Comment by danielyeh-meepshop** [comment]
- antd@4.24.8
- react@18.2.0
- react@18.2.0

**Comment by Alimardon19** [comment]
I have this problem too. Has anyone found an answer to this problem?

**Comment by popmanhe** [comment]
I am using antd 5.13.2 and react 18.2.0 and it works.

Please try to upgrade to antd v5 and see if it works for you.

**Comment by jaxxreal** [comment]
> I have this problem too. Has anyone found an answer to this problem?

The solution I found on some other thread is:

**Remove** react, react-dom, antd packages. **Install** the same versions of packages.

After remove/install I got it working as a charm!

I'm on react@18.2, react-dom@18.2 and antd@4.24.15.

Hope it will help for those who is on antd@4 and want bump their react version.

**Comment by MichaelJHaywood** [comment]
I'm having this issue occur too but with Buttons. If I use `5.1.2` onwards then clicking buttons will cause an infinite loop and freeze up the app. Any older versions work fine. Using React 17.0.2. 
This only happens in dev mode. Running in production mode in Webpack works fine.

**Comment by ilhamwd** [comment]
Why is this closed? Still an issue on 
"antd": "^5.7.3"
"react": "^18.2.0"

**Comment by ofelia-bb** [comment]
Got it fixed by adding this:

```
"resolutions": {
  "rc-tooltip": "5.3.1",
  "rc-picker": "2.6.9",
  "rc-trigger": "5.3.4"
}
```

Thanks to @pkocherov-xometry and https://github.com/ant-design/ant-design/issues/34890#issuecomment-1701222426

**Comment by Alimardon19** [comment]
success
