### ISSUE TITLE
Sider menu theme transition is not syncronized with other components

### ISSUE THREAD

**Issue by healplease** [ant-design/ant-design#40379]
### Reproduction link

[https://github.com/healplease/healplease.github.io/blob/reacty/src/components/common/Sidebar.jsx](https://github.com/healplease/healplease.github.io/blob/reacty/src/components/common/Sidebar.jsx)

### Steps to reproduce

1. Add Sider from Layout component to the page
2. Pass "theme" argument to the Sider component
3. Add Menu component somewhere in Sider
4. Pass "theme" argument to the Menu component
5. Create a switch that will control the theme 
6. Try to switch between different themes

### What is expected?

There is no visible difference in the colors transition between components when changing theme

### What is actually happening?

There is difference between color transition in Menu compared to other components - Menu seems to transition a bit later

| Environment | Info |
| --- | --- |
| antd | 5.1.2 |
| React | 18.2.0 |
| System | Windows 11 |
| Browser | Google Chrome 109.0.5414.75 |

---
You can test it on https://healplease.github.io/ (on the sider menu expand "Appearance" item and click on switch, you should be able to see delay in transitions between different components)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/41993

**Comment by Kamahl19** [comment]
@afc163 this is actually still not working correctly for the Sidebar trigger component that hide the sidebar. It transitions slower then the rest of the sidebar. 
![trigger transition](https://github.com/ant-design/ant-design/assets/1591293/8d12e2e9-e4e1-4024-9db4-f915b40bbd24)

**Comment by afc163** [comment]
@Kamahl19 Could you provide a codesandbox?
