### ISSUE TITLE
Popup closed when clicking on icon inside the content

### ISSUE THREAD

**Issue by Ilanrot** [ant-design/ant-design#42104]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-darkness-3e4h6p?file=/src/App.js)

### Steps to reproduce

1. click on the title to open the popup
2. click on expand button inside the popup content
3. popup will close

### What is expected?

we expect the popup should stay open 

### What is actually happening?

the popup closed

| Environment | Info |
| --- | --- |
| antd | 5.4.6 |
| React | 18.2 & 17 |
| System | mac m2 |
| Browser | chrome |

---
this behavior only happens when clicking on the icon , if we click on any other place the popup will stay open

quick fix for me was to wrap the content with a div and prevent bubbling but its seems like a bug and not something that I should add manually
```typescript
      <Popover
        content={
          <div onClick={(e) => e.stopPropagation()}>
            <Tree
              showLine
              showIcon
              defaultExpandedKeys={["0-0-0"]}
              treeData={treeData}
            />
          </div>
        }
        placement="buttom"
        trigger="click"
      >
        <h1>click to open popup</h1>
      </Popover>
```

**Comment by BoyYangzai** [comment]
👍

**Comment by Ilanrot** [comment]
> bugfix/popup_inner_click_issue_#42104 Ilanrot/ant-design#1

I opened a PR for that [#42107](https://github.com/ant-design/ant-design/pull/42107)

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/trigger/pull/376

**Comment by Ilanrot** [comment]
> Fixed in [react-component/trigger#376](https://github.com/react-component/trigger/pull/376)

still not fixed. having the same issue after updating the package
