### ISSUE TITLE
TextArea throws "Cannot read properties of null (reading 'textArea')"

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#43615]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-textarea-runtime-error-d3xdfs)

### Steps to reproduce

Hard to summarize. See repro link. Please note that you may try multiple times to repro it.

### What is expected?

TextArea does not throw error.

### What is actually happening?

TextArea throws `Cannot read properties of null (reading 'textArea')` occasionally.
<img width="452" alt="image" src="https://github.com/ant-design/ant-design/assets/18240847/476de7ce-669c-45bd-a9bb-ec480347f101">

| Environment | Info |
| --- | --- |
| antd | 5.7.0 |
| React | 18.2.0 |
| System | MacOS |
| Browser | Chrome 112.0.5615.121 |

**Comment by manivsh** [comment]
I have an `<Input.TextArea />` in a modal*. the null point exception is thrown every time the modal is not open after the first mount. 


*not antd modal, but my own component that has "display:none" + [Freeze](https://github.com/software-mansion/react-freeze) when `open=false`

**Comment by bombillazo** [comment]
Thanks!

**Comment by panlina** [comment]
When will this be merged into antd package? I don't see it in recent 5.7.1 and 5.7.2 versions.

**Comment by Gowtamkumar** [comment]
solved this problem?

**Comment by panlina** [comment]
> I am face this same problem.. solved this problem?

Yes. Solved in 5.7.3.

**Comment by fatihgnc** [comment]
> When will this be merged into antd package? I don't see it in recent 5.7.1 and 5.7.2 versions.

it still isn't merged into antd and i am still facing this error.

**Comment by panlina** [comment]
> > When will this be merged into antd package? I don't see it in recent 5.7.1 and 5.7.2 versions.
> 
> it still isn't merged into antd and i am still facing this error.

Should have been fixed in 5.7.3.

**Comment by AlessandroGambaro** [comment]
This error is back with version 5.11.0

**Comment by afc163** [comment]
@AlessandroGambaro Fixed in https://github.com/react-component/textarea/releases/tag/v1.5.2

**Comment by kimhandole** [comment]
the error still exist with version 5.11.1

**Comment by afc163** [comment]
@kimhandole Please remove yarn.lock and package-lock.json and reintall again.

**Comment by kimhandole** [comment]
@afc163  wow it is gone, thank you!

**Comment by afc163** [comment]
@kimhandole Could you provide a reproduce codesandbox?
