### ISSUE TITLE
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?

### ISSUE THREAD

**Issue by Yuezi32** [ant-design/ant-design#43973]
### Reproduction link

[https://ant-design.antgroup.com/components/modal-cn](https://ant-design.antgroup.com/components/modal-cn)

### Steps to reproduce

在开发Chrome Extension的content script部分中，引入了Antd的Modal组件。
第一次打开Modal时，会出现以下警告：
```
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
    at svg
    at jv (chrome-extension://jeopghjaogfpilgeodjdinacllinclbn/content.js:302:423)
    at span
    at chrome-extension://jeopghjaogfpilgeodjdinacllinclbn/content.js:302:1259
    at CloseOutlined
    at span
    at button
```
在排除了其他干扰代码的情况下，只单纯使用Modal组件，问题依旧。

经尝试，对Modal设置closeIcon={null}后，即取消右上角的关闭图标，Warning不再出现。

### What is expected?

不再出现此问题导致的Warning。

### What is actually happening?

第一次打开Modal时，会出现以下警告：
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?

| Environment | Info |
| --- | --- |
| antd | 5.8.1 |
| React | 18.2.0 |
| System | All |
| Browser | Chrome 115.0.5790.114 |

**Comment by zombieJ** [comment]
给个重现看看，这个应该已经修复了。

**Comment by jlissner** [comment]
I ran into this issue as well, you need to update your `@ant-design/icons` package

**Comment by Yuezi32** [comment]
> 给个重现看看，这个应该已经修复了。

十分抱歉，上报issue时，填错了antd版本号，问题在5.8.0出现，升级到5.8.1后问题已修复。
感谢各位！Thanks for everyone!

**Comment by tuntun0609** [comment]
在4.24.13也出现了同样的问题
https://codesandbox.io/s/antd-reproduction-template-forked-s8pqvq?file=/index.js

**Comment by yoyo837** [comment]
Reopen for 4.x

**Comment by jayconscious** [comment]
mark

**Comment by MadCcc** [comment]
Fixed in `@ant-design/icons@4.8.1`

**Comment by D3strukt0r** [comment]
I tried 4.8.1 and still had the error

**Comment by GavinThomas1192** [comment]
I'm still experiencing this using `@ant-design/icons": "5.2.5`.

**Comment by yoyo837** [comment]
> 在4.24.13也出现了同样的问题 https://codesandbox.io/s/antd-reproduction-template-forked-s8pqvq?file=/index.js

Please provide a reproduction and open a new issue for that.

**Comment by emilioponce** [comment]
Hi, same problem for us with   "antd": "4.16.13".

Not sure why a recent change in the icons dependency is changing code in an old fixed version of antd. Maybe I'm missing something, but, why inner dependencies are not fixed? thanks

**Comment by wanglei1900** [comment]
my suggestion is tring to update your @ant-design/icons to the latest.

**Comment by kevin262516** [comment]
> Fixed in `@ant-design/icons@4.8.1`

Very useful

**Comment by ivanabovin** [comment]
updating `@ant-design/icons` from `5.1.4` to `5.2.5` helped me

**Comment by geektcp** [comment]
version 
4.8.1
5.2.5 
bug

**Comment by fpsqdb** [comment]
antd 4.24.14 + icons 5.2.6 还是报错

**Comment by kaisawind** [comment]
> antd 4.24.14 + icons 5.2.6 还是报错

delete yarn.lock or package.lock. 
re npm or yarn.

**Comment by jimmykane** [comment]
Hi this issue is still out there. Nothing helps

**Comment by kang-N-S** [comment]
"@ant-design/icons": "^5.2.6","antd": "^4.22.2",Also reporting an error
