### ISSUE TITLE
Checkboxes crash Chrome when placed in a Popover within a Modal

### ISSUE THREAD

**Issue by emandres** [ant-design/ant-design#48296]
### Reproduction link

[https://codepen.io/Eric-Andres/pen/wvZyxBV](https://codepen.io/Eric-Andres/pen/wvZyxBV)

### Steps to reproduce

Open popover within a modal, click checkbox

### What is expected?

The checkbox should work normally

### What is actually happening?

The Chrome tab crashes (Aw snap, Error 5)

| Environment | Info |
| --- | --- |
| antd | 5.16.1 |
| React | 18 |
| System | MacOS 14.4.1 |
| Browser | Chrome 123 |

**Comment by shresthadeepesh** [comment]
I am not facing the issue regarding this,also it is working fine in the reproduction link.

**Comment by afc163** [comment]
> I am not facing the issue regarding this,also it is working fine in the reproduction link.

Me neither.

**Comment by ys0516** [comment]
I tried running it on the latest version of Chrome and it crashed.
chrome version：123.0.6312.107

**Comment by emandres** [comment]
Yeah, I'm not sure of an exact way to reproduce on any given machine. It crashes consistently on my desktop (M2 Mac Studio), and sporadically on my laptop (M3 Macbook Air)

**Comment by LAWTED** [comment]
The issue consistently occurs on some Macs with the M2 chip, while others do not experience this problem.

**Comment by LAWTED** [comment]
I downgrade my chrome version to 121.0.6167.184 to solve this. [link](https://google-chrome.cn.uptodown.com/mac/download/123646085)

**Comment by afc163** [comment]
@emandres Could you try again on Chrome 124?

**Comment by YardWill** [comment]
It seems that it has been fixed in chrome v125.
[link](https://support.google.com/chrome/thread/269559069?hl=en&msgid=270609737)

**Comment by emandres** [comment]
@afc163 still broken on 124. Will check once 125 has released
