### ISSUE TITLE
⚠️ Some components throw `findDOMNode is deprecated and will be removed` in React 18.3 / 19

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#48709]
Related links:
- https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-finddomnode
- https://github.com/facebook/react/commit/c3b283964108b0e8dbcf1f9eb2e7e67815e39dfb

Components to fix
- [x] Menu: https://github.com/ant-design/ant-design/issues/48646
- [x] Tooltip / Select: https://github.com/ant-design/ant-design/issues/48565
- [x] Dropdown: https://github.com/ant-design/ant-design/issues/42926
- [x] Dropdown / Form: https://github.com/ant-design/ant-design/issues/46113
- [x] FloatButton: https://github.com/ant-design/ant-design/issues/46326
- [x] Input: https://github.com/ant-design/ant-design/issues/42994
- [x] Anchor: https://github.com/ant-design/ant-design/issues/48812

**Comment by 1yasa** [comment]
Button组件在最近的react experimental中报`legacyRender`错误（点击即报错），这个错误似乎来自于`rc-util`。

https://github.com/react-component/util/blob/b2016407b7b14353f7b209d8a37df875f0dd0f11/src/React/render.ts#L17

<img width="712" alt="截屏2024-04-30 14 13 42" src="https://github.com/ant-design/ant-design/assets/127166080/9b782724-c277-4a6f-b215-58a2a69886eb">

这种写法会存在版本问题（现在react的一些dom方法从react-dom/client导入）。

**Comment by shamseer-ahammed** [comment]
+1

**Comment by Rising-Pstar** [comment]
+1

**Comment by Soskxkakr** [comment]
+1

**Comment by jesse996** [comment]
+10086

**Comment by wanpan11** [comment]
https://github.com/ant-design/ant-design/issues/48809

**Comment by ppjjzz** [comment]
> react-dom/client



> Button组件在最近的react experimental中报`legacyRender`错误（点击即报错），这个错误似乎来自于`rc-util`。
> 
> https://github.com/react-component/util/blob/b2016407b7b14353f7b209d8a37df875f0dd0f11/src/React/render.ts#L17
> 
> <img alt="截屏2024-04-30 14 13 42" width="712" src="https://private-user-images.githubusercontent.com/127166080/326690235-9b782724-c277-4a6f-b215-58a2a69886eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTAwNzIsIm5iZiI6MTcxNTA4OTc3MiwicGF0aCI6Ii8xMjcxNjYwODAvMzI2NjkwMjM1LTliNzgyNzI0LWMyNzctNGE2Zi1iMjE1LTU4YTJhNjk4ODZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxMzQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTNiYTVlMjcwNjcwZGQ3ZGQxNDBiMDk4Y2E5ZTc5ZTg3OWNlOWVjMDY4NWFhMTY2OTNmNzRlMzM0OTI4OWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OmkMetWq_YPPJ7VUR7R3Jp9gQyXm8pP2qO148trwCWQ">
> 这种写法会存在版本问题（现在react的一些dom方法从react-dom/client导入）。

这个会导致一些antd组件无法在react 19下使用，例如message

**Comment by p-a** [comment]
+1

**Comment by osherasfa** [comment]
+1111

**Comment by xiaoxustudio** [comment]
+1，我用的是18.2.0，在无严格模式下，复制官网的`<Button type="dashed">Dashed Button</Button>`按钮组件就会报错

**Comment by pqhuy98** [comment]
+1

**Comment by zhouccccc** [comment]
any update?

**Comment by tahafatih** [comment]
+1

**Comment by 0fan** [comment]
官方有计划修复吗

**Comment by vtur** [comment]
+1

**Comment by ppjjzz** [comment]
升级到5.17.2版本后使用 Menu 组件还是会报这个警告

**Comment by hiql** [comment]
这个问题依久很多😮‍💨

react-dom.development.js:86 
 Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at SingleObserver (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:1731:24)
    at ResizeObserver3 (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:1808:24)
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:21861:34
    at Tooltip2 (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:27092:32)
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:27734:16
    at MenuItem2 (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:31294:5)
    at div
    at InheritableContextProvider (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:29565:23)
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:30705:43
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:32537:29
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:32652:45
    at div
    at aside
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:31079:16
    at div
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:63544:16
    at Layout
    at main
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:63525:16
    at Content
    at div
    at http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:63544:16
    at Layout
    at NotesPage (http://localhost:7718/app/routes/app.tsx:118:16)
    at RenderedRoute (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:404:5)
    at Outlet (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:738:26)
    at App
    at LocaleProvider (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:4192:13)
    at MotionWrapper (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:7577:5)
    at ProviderChildren (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:7687:5)
    at ConfigProvider (http://localhost:7718/node_modules/.vite/deps/antd.js?v=515c6aff:7959:27)
    at body
    at html
    at Layout (http://localhost:7718/app/root.tsx:18:3)
    at RenderedRoute (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:404:5)
    at RenderErrorBoundary (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:364:5)
    at DataRoutes (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:1393:5)
    at Router (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:745:15)
    at RouterProvider (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:1210:5)
    at RemixErrorBoundary (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:3455:5)
    at RemixBrowser (http://localhost:7718/node_modules/.vite/deps/@remix-run_react.js?v=515c6aff:4112:46)

**Comment by yoyo837** [comment]
Similar to #48646

**Comment by wanpan11** [comment]
This may be one of the issues 

- https://github.com/react-component/motion/issues/50

**Comment by ppjjzz** [comment]
能否在4.x版本也修复这个问题？

**Comment by wanpan11** [comment]
> 能否在4.x版本也修复这个问题？

锁定 react 版本 18,2.0 就行了 4.x停止维护了

**Comment by shanmugarajbe** [comment]
Please include the following components too

- [ ] Tour

**Comment by raulmarindev** [comment]
So, if I understand this right, every component from the react-component library that uses findDOMNode is affected, correct?

https://github.com/search?q=org%3Areact-component+findDOMNode&type=code

**Comment by yoyo837** [comment]
There are some fixes in #48958.

**Comment by bombillazo** [comment]
> There are some fixes in #48958.

Hopefully, they will be released soon!

**Comment by bombillazo** [comment]
5.17.3 was released! Hopefully this is fixed

**Comment by loqbudokai3** [comment]
> 5.17.3 was released! Hopefully this is fixed

While it did fix for a lot of components, still happens on my end, using the Select component

**Comment by bryanltrang** [comment]
fixed for me using 5.17.3!

**Comment by zombieJ** [comment]
@loqbudokai3, pls feel free to create new issue with reproduce that we can track the problem : )

**Comment by tim-richter** [comment]
Also fixed for us in 5.17.3.

Just as a heads up for people getting the warning anyway: Antd will **still** fallback to `findDOMNode`, if you don't forward the ref correctly to your custom components. You need to pass the ref to the child of `Tooltip` for example. Same with Popover etc.

Might be worth to completely remove this fallback behavior, when React 19 is production ready, but for now that's the behavior that I noticed for some components.

**Comment by AariefMohideen** [comment]
+1
Using with 5.17.3 but still getting warning. React version: 18.3.*

**Comment by zhe-he** [comment]
+1
Using with 5.17.4 but still getting warning. React version: 18.3.*

**Comment by gaspire** [comment]
+1

**Comment by yoyo837** [comment]
issue reproduction, please.

**Comment by boomsi** [comment]
React@18.2 
Antd@5.17.3

react-dom.development.js:86 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper4 which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:17559:24
    at DomWrapper4 (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:1403:5)
    at SingleObserver (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:1446:24)
    at ResizeObserver3 (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:1523:24)
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:17579:34
    at Dropdown (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:24952:28)
    at Dropdown2 (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:30213:5)
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:17559:24
    at DomWrapper4 (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:1403:5)
    at SingleObserver (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:1446:24)
    at ResizeObserver3 (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:1523:24)
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:17579:34
    at Tooltip2 (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:22602:32)
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:23371:16
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:23754:16
    at li
    at ul
    at div
    at List (http://localhost:8088/src/pages/draw-editor/additional/list/index.tsx:27:3)
    at div
    at div
    at AIImage (http://localhost:8088/src/pages/draw-editor/additional/ai.tsx:41:3)
    at div
    at div
    at Additional (http://localhost:8088/src/pages/draw-editor/additional/index.tsx:43:20)
    at div
    at div
    at div
    at DrawEditor (http://localhost:8088/src/pages/draw-editor/index.tsx:40:19)
    at RenderedRoute (http://localhost:8088/node_modules/.vite/deps/react-router-dom.js?v=8669f420:3133:5)
    at Outlet (http://localhost:8088/node_modules/.vite/deps/react-router-dom.js?v=8669f420:3482:26)
    at QueryClientProvider (http://localhost:8088/node_modules/.vite/deps/@tanstack_react-query.js?v=8f7c5241:2590:3)
    at ErrorBoundary (http://localhost:8088/src/components/errorboundary/index.tsx:6:5)
    at div
    at main
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:28258:16
    at Content
    at div
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:28277:16
    at Layout
    at main
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:28258:16
    at Content
    at div
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:28277:16
    at Layout
    at div
    at http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:28277:16
    at Layout
    at LocaleProvider (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:2063:13)
    at MotionWrapper (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:4265:5)
    at ProviderChildren (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:4374:5)
    at ConfigProvider (http://localhost:8088/node_modules/.vite/deps/antd.js?v=2b79ccf1:4612:27)
    at App (http://localhost:8088/src/layout/App.tsx:78:3)
    at RenderedRoute (http://localhost:8088/node_modules/.vite/deps/react-router-dom.js?v=8669f420:3133:5)
    at RenderErrorBoundary (http://localhost:8088/node_modules/.vite/deps/react-router-dom.js?v=8669f420:3093:5)
    at DataRoutes (http://localhost:8088/node_modules/.vite/deps/react-router-dom.js?v=8669f420:3417:5)
    at Router (http://localhost:8088/node_modules/.vite/deps/react-router-dom.js?v=8669f420:3489:15)
    at RouterProvider (http://localhost:8088/node_modules/.vite/deps/react-router-dom.js?v=8669f420:3373:5)
    at Provider (http://localhost:8088/node_modules/.vite/deps/react-redux.js?v=19ce1cd2:1286:3)
    at StyleProvider2 (http://localhost:8088/node_modules/.vite/deps/chunk-ZVUDHHES.js?v=50ae06bd:279:24)

**Comment by gaspire** [comment]
<img width="782" alt="image" src="https://github.com/ant-design/ant-design/assets/49259119/3ef9cec1-7096-4c4f-a867-25f64a2fad21">

**Comment by Allenice** [comment]
使用 Tooltip 组件也会报这个错 
![image](https://github.com/ant-design/ant-design/assets/2650994/61cdf4bb-85fa-4e62-93b3-fd601e67b8de)

**Comment by timphamcmc** [comment]
> issue reproduction, please.

I got it when using the **Transfer** (React + Vite)
![image](https://github.com/ant-design/ant-design/assets/108319981/46ce71fa-c278-489d-b8f4-b17f103ee866)

**Comment by ASaludo** [comment]
Reproduce when I use the Menu component 
```
"antd": "5.18.0",
"react": "18.3.1",
```

**Comment by neuodev** [comment]
+1

**Comment by qnnp-me** [comment]
+1

**Comment by 11bit** [comment]
What if my component returns null, so  it can't have a ref? Example:

```
function App() {
  return (
      <Tooltip title="test">
          <NullComponent />
      </Tooltip>
  );
}

function NullComponent() {
    return null;
}
```

Of course this is synthetic example. But in large applications  it is a common thing for a component to early return `null` in some circumstances. You don't expect that this early return can be anything bad. But when wrapped in Tooltip or Dropdown it will print warnings or even crash in react 19.

**Comment by ByteTerminator** [comment]
![image](https://github.com/ant-design/ant-design/assets/42922398/2302fc6a-561a-492a-a9ba-e8d8ffd11f4b)
 "react": "^18.2.0",
 "react-dom": "^18.2.0",
 "antd": "^4.24.15",
同样有类似问题，希望尽快修复

**Comment by Harmew** [comment]
+1

**Comment by fnoopv** [comment]
> ![image](https://private-user-images.githubusercontent.com/42922398/338395847-2302fc6a-561a-492a-a9ba-e8d8ffd11f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzQ2NDAsIm5iZiI6MTcxODMzNDM0MCwicGF0aCI6Ii80MjkyMjM5OC8zMzgzOTU4NDctMjMwMmZjNmEtNTYxYS00OTJhLWE5YmEtZThkOGZmZDExZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAzMDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YzAxMGJlMzJkMWU4MGI2MDI2NWYwNjY2YTQzZTYyNTcwOTkzOGM3NmQwNzAxOWVhNjEwMDdlMmM2ODE1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.01P09LUrHP2TYBkeeiyi0rAxyz23yg9DBq_d5tQIKpg) "react": "^18.2.0", "react-dom": "^18.2.0", "antd": "^4.24.15", 同样有类似问题，希望尽快修复，下面是一个空白项目，引入Table ![image](https://private-user-images.githubusercontent.com/42922398/338481565-218fe5df-720e-4f9c-bde4-1fba75452c0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzQ2NDAsIm5iZiI6MTcxODMzNDM0MCwicGF0aCI6Ii80MjkyMjM5OC8zMzg0ODE1NjUtMjE4ZmU1ZGYtNzIwZS00ZjljLWJkZTQtMWZiYTc1NDUyYzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAzMDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkODk2NmVmYTJiZjFmZWM4ODUxZjhkNjRkYTk4YzVjNDZhNjI5MDY3ZjU1MTJlZTcxM2E3MTMxODFhMTI0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PimAzA_zbN4dnCKk5He-N3Em38nZZJqvLX3FNFV23mc)

v4停止维护了, [公告](https://ant.design/docs/blog/v4-ood-cn)

**Comment by sh0umik** [comment]
+1

**Comment by ttc0419** [comment]
看所有提到的MR已经合并，也使用了最新5.18.1，但是还是有
```
Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
SingleObserver@http://localhost:5173/node_modules/.vite/deps/chunk-DJVVTTSA.js:715:23
ResizeObserver2@http://localhost:5173/node_modules/.vite/deps/chunk-DJVVTTSA.js:792:23
Trigger@http://localhost:5173/node_modules/.vite/deps/chunk-DJVVTTSA.js:3139:33
Tooltip2@http://localhost:5173/node_modules/.vite/deps/chunk-IV56FG2I.js:173:31
Tooltip@http://localhost:5173/node_modules/.vite/deps/chunk-IV56FG2I.js:1429:12
MenuItem@http://localhost:5173/node_modules/.vite/deps/chunk-IV56FG2I.js:1571:12
SubMenu@http://localhost:5173/node_modules/.vite/deps/chunk-DJVVTTSA.js:3811:23
SubMenu@http://localhost:5173/node_modules/.vite/deps/chunk-2QPJZJWC.js:31:12
div
InheritableContextProvider@http://localhost:5173/node_modules/.vite/deps/chunk-DJVVTTSA.js:1727:22
@http://localhost:5173/node_modules/.vite/deps/chunk-DJVVTTSA.js:4329:42
@http://localhost:5173/node_modules/.vite/deps/chunk-XHE2WXLT.js:1176:37
div
aside
Sider@http://localhost:5173/node_modules/.vite/deps/chunk-JQ6VXYKH.js:81:12
div
@http://localhost:5173/node_modules/.vite/deps/chunk-IKHYHOEP.js:318:23
Layout
xxx@http://localhost:5173/src/views/xxx.tsx:37:47
yyy
RenderedRoute@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js:3638:11
RenderErrorBoundary@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js:3595:10
DataRoutes@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js:4747:12
Router@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js:4019:12
RouterProvider@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js:4564:11
```

**Comment by yoyo837** [comment]
Again. If anyone still get related problems after updating to version 5.17.3 or above, please provide the reproduction link to help us solve it. Thank you.

**Comment by 11bit** [comment]
Hey @yoyo837, What about [my question](https://github.com/ant-design/ant-design/issues/48709#issuecomment-2158854857) regarding using a component that returns null inside Tooltip. Here is a [reproduction link](https://stackblitz.com/edit/vitejs-vite-cqyvgc?file=src%2FApp.tsx). Do you have any plans on handling this case? Thanks!

**Comment by yoyo837** [comment]
> Hey @yoyo837, What about [my question](https://github.com/ant-design/ant-design/issues/48709#issuecomment-2158854857) regarding using a component that returns null inside Tooltip. Here is a [reproduction link](https://stackblitz.com/edit/vitejs-vite-cqyvgc?file=src%2FApp.tsx). Do you have any plans on handling this case? Thanks!

Thank you, we will check it.

**Comment by diegonc** [comment]
Menu is still not fixed for the children use case. Here is a reproducer: https://stackblitz.com/edit/react-cp1c8b?file=src%2FApp.js

I understand if children use case, being deprecated, won't get bug fixes or updates. But I thought I should report here as [Refine.dev](https://refine.dev) is using it and they find it hard to replace (see  https://github.com/refinedev/refine/issues/5393#issuecomment-1864324099 )

**Comment by LJH520** [comment]
Using with 5.17.4 but still getting warning. React version: 18.2.*

**Comment by zombieJ** [comment]
Hi @11bit,
It's by design to fallback to use `findDOMNode` if children **not support** `ref` since Tooltip need to get dom node to make sure the align position. The correct way is let your sub component support `ref` for parent tracking.

-----

Hi @diegonc,

I check the https://github.com/refinedev/refine/issues/5393#issuecomment-1864324099 . It's not an impossible transformation to refactor with `items` but need more work for refactoring. antd deprecated JSX structure since we need follow the React steps which means origin JSX structure is not a best practice for function component (it will break the memo perf enhancement). So as your comment, if you want to enjoy the benefits of the latest React, some refactor is necessary. We've do our best to reduce the panic of upgrade but sometime have to.

**Comment by yoyo837** [comment]
Thanks to @zombieJ  for investigating. This issue will be closed if there are no other useful reproductions.

**Comment by 11bit** [comment]
> Hi @11bit,
It's by design to fallback to use findDOMNode if children not support ref since Tooltip need to get dom node to make sure the align position. The correct way is let your sub component support ref for parent tracking.

Hey @zombieJ, Thanks for response! I apologize for incomplete example. I understand the thing about findDOMNode, but I am talking about another edge case. 

I have a bunch of components that are wrapped in Tooltip and that can sometimes return `null`. In this case it is impossible to support a ref because there is no container (what I actually want is to render nothing). This is an example of this component:

```
const MyComponent = forwardRef(({ someCondition }, ref) => {
  if (someCondition) {
    // In this branch I can not make a ref and so I get a warning
    return null;
  }

  // Here everything works ok
  return <div ref={ref}>Component rendered</div>;
});
```
([Stackblitz](https://stackblitz.com/edit/vitejs-vite-cqyvgc?file=src%2FApp.tsx))

I understand that returning null can be slightly incorrect. But it worked very well before: tooltip is just not rendered if it doesn't have a child. So it is a breaking change for us and it is quite hard to refactor because now I have to extract conditions out of every component and not render Tooltip at all.

**Comment by yoyo837** [comment]
@11bit Does [this](https://stackblitz.com/edit/vitejs-vite-yvvh83?file=src%2FApp.tsx) can solve your problem?

**Comment by 11bit** [comment]
> @11bit Does [this](https://stackblitz.com/edit/vitejs-vite-yvvh83?file=src%2FApp.tsx) solve your problem?

It will work, but it is pretty big refactoring for us. This is why I want to know ant-design team's thoughts on this before doing any rewrites. 

Another consideration is that fallback to `findDOMNode` is temporary anyway, since they removed it in React 19. So I wonder how ant-design will work in future. Presumably warning will be gone, and I will be allowed to return null again?

**Comment by zombieJ** [comment]
@11bit,
React can not tell that current node is empty dom. For parent it will still get the `children` is a valid React Element. This `findDOMNode` will still be the fallback way on React 18.

For React 19, we will follow the rules of React. If it removed in official version, we will also remove the fallback by the 19 (but still provide the fallback support in early React version to avoid break change).

**Comment by 11bit** [comment]
I see. Thanks for the answer!

**Comment by jiaozhiye** [comment]
![image](https://github.com/ant-design/ant-design/assets/22720488/9032faa7-fbd1-4518-9dba-eaa2f5264ce8)
这个问题解决了吗？我这里react18.3.1还是报这个警告！

**Comment by gaspire** [comment]
我也是，怎么关闭了

**Comment by raulmarindev** [comment]
It was closed because no reproduction was added. A reproduction is needed for them to fix it.

**Comment by zhe-he** [comment]
<img width="1188" alt="image" src="https://github.com/ant-design/ant-design/assets/11306583/f867aa75-0668-4e2b-8f6d-6a9dfc2a902e">

[bug demo](https://codesandbox.io/p/devbox/toolbar-finddomnode-x6s4d6?file=%2Fsrc%2FApp.tsx%3A13%2C2)

**Comment by wanpan11** [comment]
> @11bit, React can not tell that current node is empty dom. For parent it will still get the `children` is a valid React Element. This `findDOMNode` will still be the fallback way on React 18.
> 
> For React 19, we will follow the rules of React. If it removed in official version, we will also remove the fallback by the 19 (but still provide the fallback support in early React version to avoid break change).

往上翻翻 答案就在上面 https://github.com/ant-design/ant-design/issues/48709#issuecomment-2181951361

**Comment by jiaozhiye** [comment]
> Hi @11bit, It's by design to fallback to use `findDOMNode` if children **not support** `ref` since Tooltip need to get dom node to make sure the align position. The correct way is let your sub component support `ref` for parent tracking.
> 
> Hi @diegonc,
> 
> I check the [refinedev/refine#5393 (comment)](https://github.com/refinedev/refine/issues/5393#issuecomment-1864324099) . It's not an impossible transformation to refactor with `items` but need more work for refactoring. antd deprecated JSX structure since we need follow the React steps which means origin JSX structure is not a best practice for function component (it will break the memo perf enhancement). So as your comment, if you want to enjoy the benefits of the latest React, some refactor is necessary. We've do our best to reduce the panic of upgrade but sometime have to.

![image](https://github.com/ant-design/ant-design/assets/22720488/8181f958-d254-4e97-a347-b0a237e27184)
![image](https://github.com/ant-design/ant-design/assets/22720488/653acd14-3f38-49a8-aedb-2d60b6f1b2d9)
If the Portal sub component is wrapped in the Trigger, an error will be reported.May I ask how to solve this problem?

**Comment by wanpan11** [comment]
Why do we need to use it this way? getTooltipContainer can modify the mounting node。

![image](https://github.com/ant-design/ant-design/assets/38714194/fd2974ae-0ab9-4594-a9b5-c353a2bb0801)

**Comment by wanpan11** [comment]
I think you can consider modifying the structure. The Trigger component should be placed inside

**Comment by youwasborntodo** [comment]
when i downgraded the react and react-dom version to 18.2.0, the problem was resolved

**Comment by shenshouer2916** [comment]
downgraded the "@ant-design/pro-components" version to "^2.3.57", the problem was resolved

**Comment by sangxiaolong** [comment]
ant design 5.19.0 react 18.0.33 依然有这个错误提醒

**Comment by zhe-he** [comment]
> ant design 5.19.0 react 18.0.33 依然有这个错误提醒

添加空的<>来解决吧。
例子：
```jsx
// before:  Some components throw findDOMNode is deprecated and will be removed in React 18.3 / 19](https://github.com/ant-design/ant-design/issues/48709#top)
<S>
     <C></C>
</S>

// after:
<S>
     <>
         <C></C>
     </>
</S>
```

**Comment by xyovo** [comment]
> > 能否在4.x版本也修复这个问题？
> 
> 锁定 react 版本 18,2.0 就行了 4.x停止维护了

感谢，有帮助

**Comment by kangwuyi** [comment]
> > <img alt="图像" width="1188" src="https://private-user-images.githubusercontent.com/11306583/344582583-f867aa75-0668-4e2b-8f6d-6a9dfc2a902e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjM2MDQsIm5iZiI6MTcxOTgyMzMwNCwicGF0aCI6Ii8xMTMwNjU4My8zNDQ1ODI1ODMtZjg2N2FhNzUtMDY2OC00ZTJiLThmNmQtNmE5ZGZjMmE5MDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA4NDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMDExOTQ3MjM4NjNmOTYyNzRhNWQ0MWNhNzEwODM4ZjgyNjU0NjExYjhmOGI1YzQ4NzU0MTcwOGNkOGZjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fcKE0NhJJhkdayBVyy8n-QddggJc9XYaXJe5PFuSQEg">
> > [错误演示](https://codesandbox.io/p/devbox/toolbar-finddomnode-x6s4d6?file=%2Fsrc%2FApp.tsx%3A13%2C2)
> 
> React18.3都发布好几个月了，啥都没人处理这个问题呢？

人都被优化了吧。。。

**Comment by dperetti** [comment]
Still happening!
```
Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at SingleObserver (webpack-internal:///./node_modules/rc-resize-observer/es/SingleObserver/index.js:21:24)
    at ResizeObserver (webpack-internal:///./node_modules/rc-resize-observer/es/index.js:24:24)
    at eval (webpack-internal:///./node_modules/@rc-component/trigger/es/index.js:61:34)
    at Tooltip (webpack-internal:///./node_modules/rc-tooltip/es/Tooltip.js:23:32)```

**Comment by kaiyoma** [comment]
I am also still seeing this in the latest version. I've filed a new issue here: https://github.com/ant-design/ant-design/issues/51107

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/51101/files


### Why does the warning `findDOMNode is deprecated` sometimes appear in strict mode?

This is due to the implementation of `rc-trigger`. `rc-trigger` forces children to accept ref, otherwise it will fall back to findDOMNode, so children need to be native html tags. If not, you need to use `React.forwardRef` transparently passes `ref` to native html tags.

- `findDOMNode is deprecated` reproduce: <https://codesandbox.io/p/sandbox/finddomnode-c5hy96>
- Using `forwardRef` to fix: <https://codesandbox.io/p/sandbox/no-finddomnode-warning-forked-gdxczs>

**Comment by wxs77577** [comment]
https://github.com/ant-design/ant-design/issues/43064#issuecomment-2456508430

**Comment by andyyxw** [comment]
> > ant design 5.19.0 react 18.0.33 依然有这个错误提醒
> 
> 添加空的<>来解决吧。 例子：
> 
> ```js
> // before:  Some components throw findDOMNode is deprecated and will be removed in React 18.3 / 19](https://github.com/ant-design/ant-design/issues/48709#top)
> <S>
>      <C></C>
> </S>
> 
> // after:
> <S>
>      <>
>          <C></C>
>      </>
> </S>
> ```

@afc163  这个办法最简单 试了确实可行，大佬看看有没有坑

**Comment by Evavic44** [comment]
Seems like this happens on components that create some form of overlay. I got this error when passing children prop directly inside a `PopConfirm` or `Tooltip` component. Solved by wrapping children in a `div`

```tsx
import { Popconfirm } from "antd";

export function Confirm(props) {
  return (
    <Popconfirm
      title={title}
      description={description}
      onConfirm={confirm}
      onCancel={cancel}
      okText="Yes"
      cancelText="No"
    >
      <div>{props.children}</div> // wrap children in a div
    </Popconfirm>
  );
}
```

**Comment by Kelly27** [comment]
[https://ant.design/components/message](https://ant.design/components/message )
This component is also throwing the same error: `Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here` . Wrapping children with `div` does not work in this case.

**Comment by jean214chang** [comment]
[https://ant.design/components/collapse](https://ant.design/components/collapse)
Collapse component 也有相同錯誤， children 中使用空 <> 或是 <div> 仍會報錯

**Comment by xingBaGan** [comment]
给报错的组件，children 外部包裹<><>的确实可以

**Comment by jtillwickEA** [comment]
This is still a major issue as it clutters up the debug console with warning messages. Why won't this be fixed?

**Comment by Userluckytian** [comment]
> Try this:

```
       window.console.error = (...args) => {
            // 忽略包含 "findDOMNode" 的弃用警告
            if (args[0] && args[0].includes('findDOMNode is deprecated')) {
                    return;
            }
            originalError.apply(console, args);
       };
```
