### ISSUE TITLE
tagRender in select component (in tags mode) is invoked regardless of whether values are present or not

### ISSUE THREAD

**Issue by momesana** [ant-design/ant-design#48930]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-uw5tyv?file=demo.tsx)

### Steps to reproduce

Render a select in tags mode with a custom tagRender property which throws if value is undefined.

### What is expected?

I expected tagRender only to be invoked if value is defined (i. e. a valid string)

### What is actually happening?

tagRender prop is being invoked even if there is no value present (with value being set to undefined)

| Environment | Info |
| --- | --- |
| antd | 5.15.2 |
| React | 18.2.0 |
| System | linux |
| Browser | chrome |

---
The issue was introduced with antd 5.15.2 which in turn was caused by the update of rc-select to version 14.12.1 to 14.13.0 which in turn just bumped up the version of rc-trigger from 1.5.0 to 2.0.0.

**Comment by fitterfizzle** [comment]
Having the same issue

**Comment by momesana** [comment]
It's this part btw, that causes the issue: https://github.com/react-component/select/blob/ebc3f689eac9640534026fb3349e901dd55bdab6/src/Selector/MultipleSelector.tsx#L179

```ts
customizeRenderSelector(undefined, content, false, false, undefined, true)
```

**Comment by devuxer** [comment]
I just hit this and had to add a workaround to my code. This is a breaking change in the Select component.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/48930

https://github.com/react-component/select/releases/tag/v14.16.5

**Comment by devuxer** [comment]
Hi @afc163,

Thank you for working on this, but it is only partially fixed.

Now, if there is no value, `tagRender` doesn't get called. This is good.

However, when you select a value, `tagRender` gets called first with `undefined` then with the `value`. This is bad (it's still a breaking change because it requires us to check for undefined when this previously wasn't needed).

Here is the console log for my [CodePen repro](https://codepen.io/devuxer/pen/qEWVaOK?editors=0011) with the latest antd (v5.24.2):

> "selected a10"
> 
> "Calling tagRender for:" // [object Object] 
> {
>   "label": "+ 0 ...",
>   **"value": undefined,**
>   "disabled": false,
>   "closable": false,
>   "onClose": undefined,
>   "isMaxTag": true
> }
> 
> "Calling tagRender for:" // [object Object] 
> {
>   "label": "a10",
>   **"value": "a10",**
>   "disabled": undefined,
>   "closable": true,
>   "onClose": function e(e){e&&e.stopPropagation(),w(t)},
>   "isMaxTag": false
> }

Why is `tagRender` being called with undefined first, then the new value?

I am not able to reopen this issue, but it should be reopened.

**Comment by devuxer** [comment]
@afc163, Please see [previous comment](https://github.com/ant-design/ant-design/issues/48930#issuecomment-2692416075). This should be reopened.

**Comment by adam-boduch** [comment]
I have the same issue
