### ISSUE TITLE
Gap Between Tooltip Content and Arrow When Page is Zoomed

### ISSUE THREAD

**Issue by SihenZhang** [ant-design/ant-design#49107]
### Reproduction link

[https://codepen.io/SihenZhang/pen/XWwNwYZ?editors=0110](https://codepen.io/SihenZhang/pen/XWwNwYZ?editors=0110)

### Steps to reproduce

1. Set the screen resolution to `1920×1080` with a scaling setting of `100%`. The bug may manifest differently at other resolutions and scaling settings, so please follow my settings.
2. Open the reproduction link. You can also open this [fullscreen reproduction link](https://codepen.io/SihenZhang/full/XWwNwYZ).
3. Hover the mouse over the table content and observe the tooltips for different rows. Some tooltips will initially have a gap and then adjust, while others will have a persistent gap.

### What is expected?

There should be no gap between the tooltip content and the arrow, just as it appears when the page is not zoomed.

### What is actually happening?

Some tooltips will initially have a gap and then adjust, while others will have a persistent gap.
![1920*1080](https://github.com/ant-design/ant-design/assets/20498895/8b50a584-2dd6-428c-90d9-b2f4aac301fc)

| Environment | Info |
| --- | --- |
| antd | 5.17.4 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Chrome 125.0.6422.113 |

---
Changing the resolution and scaling settings will yield different results. For example, setting the resolution to `2240×1400` and the scaling to `150%` will cause most tooltips to display correctly, with only a few having a gap.
![2240*1400](https://github.com/ant-design/ant-design/assets/20498895/b8dc0eed-0b9f-4ff7-944b-67c0612a733e)

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/trigger/pull/465

**Comment by SihenZhang** [comment]
I've created a new demo on Stackblitz using `@rc-component/trigger@2.2.0`, but the issue still seems to persist.
https://stackblitz.com/edit/vitejs-vite-nrdtds
![image](https://github.com/ant-design/ant-design/assets/20498895/4e0a5c65-f97e-408a-8cad-93491296a852)

**Comment by zombieJ** [comment]
When zoomed, browser return the rect has already miss the precision. It can not trace back from js side.

**Comment by SihenZhang** [comment]
Chrome 128 has shipped an update that adjusts the `zoom` property. For more details, you can check: https://chromestatus.com/feature/5198254868529152. I believe this update should resolve the issue.
