### ISSUE TITLE
[Menu] - Warning: Accessing element.ref was removed in React 19

### ISSUE THREAD

**Issue by alaychak-hc** [ant-design/ant-design#49267]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/nice-danny-6h7ckz?file=%2Fsrc%2FApp.tsx%3A16%2C25)

### Steps to reproduce

Add a children prop to a Menu item. No warning is given if the children prop is removed. No "ref" prop is needed for a warning to appear (if children prop is provided). 

### What is expected?

No warning should appear.

### What is actually happening?

Full warning is:

Warning: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

| Environment | Info |
| --- | --- |
| antd | 5.18.0 |
| React | 19.0.0-rc.0 |
| System | Windows |
| Browser | Chrome v126.0.6468.2 |

**Comment by vylink** [comment]
This is also happening with tabs.


Environment | Info
-- | --
antd | 5.18.0
React | 19.0.0-beta-26f2496093-20240514
System | macOs Sonoma
Browser | Chrome v125.0.6422.142

**Comment by brandonfake69** [comment]
And also happening with the `<Slider />`

**Comment by tiarebalbi** [comment]
➕ 
````
app-index.tsx:30 Warning: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.
    at Wave (webpack-internal:///(app-pages-browser)/./node_modules/antd/es/_util/wave/index.js:26:13)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/antd/es/button/button.js:65:13)
    at FloatingRecordContainer (webpack-internal:///(app-pages-browser)/./src/components/FloatingRecordContainer.tsx:14:13)
    at NovoCliente (webpack-internal:///(app-pages-browser)/./src/app/(dashboard)/d/clientes/components/NovoCliente.tsx:23:76)
    at div
    at div
    at div````

**Comment by nicevlhjfihtqngkldl** [comment]
Same problem.Does the maintainer have the plan to fix this?

**Comment by zhaoguanggang1-tal** [comment]
+

**Comment by rendeyuwei** [comment]
same problem

**Comment by xqinwl** [comment]
same problem too

**Comment by aurora-lch** [comment]
react 18.3.1 antd 5.21.5

**Comment by israel-lpz** [comment]
same problem

**Comment by lyfmantle** [comment]
same problem

**Comment by rftglyv** [comment]
Same Problem

"next": "15.0.1",
"react": "^18.3.1",
"react-dom": "^18.3.1",

**Comment by jvnm-dev** [comment]
Same w/ next 15

**Comment by zahra-moradii** [comment]
Same Problem here

"next": "15.0.1",
"react": "^18.3.1",
"react-dom": "^18.3.1",

**Comment by marcelosasamoto** [comment]
I had the same problem when creating a new project using NextJS V15 which uses React 19rc. I had to install nextjs V14 which uses react 18, which Ant Design is compatible with.

"antd": "^5.21.5",
"next": "14",
"react": "18",
"react-dom": "18"

will work normally.

Otherwise, I think we should wait for an update from the Ant Design team.

**Comment by artem-bq** [comment]
Same here:
"react": "^18.3.1",
"react-dom": "^18.3.1",
"antd": "^5.21.6",
"next": "15.0.1",

**Comment by mattjin** [comment]
+1

**Comment by r0-0ky** [comment]
same problem

**Comment by rohanmaharjan247** [comment]
same problem with nextjs 15

**Comment by Yero123** [comment]
same problem

**Comment by rahulthomasdev** [comment]
+1

**Comment by codekcv** [comment]
+1

**Comment by alex-zwingli** [comment]
Same problem

**Comment by rudestewing** [comment]
Same Problem here 
```
...
    "react": "^18",
    "react-dom": "^18"
     "next": "15.0.2",
     "antd": "^5.21.6",
...
```

**Comment by gunooh** [comment]
+1
```
"react": "19.0.0-rc-69d4b800-20241021",
"react-dom": "19.0.0-rc-69d4b800-20241021",
"next": "^15.0.2",
"antd": "^5.21.5",
```

**Comment by follow-prince** [comment]
i fixed it very easy

**Comment by follow-prince** [comment]
please dm me for patch package

**Comment by Gagafeee** [comment]
Same with Button component
```
"@ant-design/nextjs-registry": "^1.0.1",
"antd": "^5.21.6",
"next": "15.0.2",
"react": "19.0.0-rc-02c0e824-20241028",
"react-dom": "19.0.0-rc-02c0e824-20241028"
```
@follow-prince Why not publish the patch ?

**Comment by follow-prince** [comment]
> Same with Button component
> 
> ```
> "@ant-design/nextjs-registry": "^1.0.1",
> "antd": "^5.21.6",
> "next": "15.0.2",
> "react": "19.0.0-rc-02c0e824-20241028",
> "react-dom": "19.0.0-rc-02c0e824-20241028"
> ```
> 
> @follow-prince Why not publish the patch ?

just dm me i will give you

**Comment by mustafamoe** [comment]
<img width="1491" alt="Screenshot 2024-11-08 at 11 57 20 AM" src="https://github.com/user-attachments/assets/86031bd4-43fc-42b8-8e9c-dd8b63d5c226">

{
  "next": "15.0.3",
  "react": "19.0.0-rc-66855b96-20241106",
  "react-dom": "19.0.0-rc-66855b96-20241106",
  "antd": "5.21.6",
  "@ant-design/nextjs-registry": "^1.0.1"
}

same issue

**Comment by nguyenngocsonit** [comment]
Same problem

**Comment by japusoy** [comment]
Same with me

**Comment by devcaiosantos** [comment]
same problem here

**Comment by zxczxcdev** [comment]
how to fix it ????

**Comment by yyhdev** [comment]
+1

**Comment by Salmandabbakuti** [comment]
+1

**Comment by bdsach** [comment]
I have the same problem.

```
"dependencies": {
    "@ant-design/icons": "^5.5.1",
    "@ant-design/nextjs-registry": "^1.0.1",
    "antd": "^5.22.1",
    "next": "15.0.3",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^22.9.0",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^9.14.0",
    "eslint-config-next": "15.0.3"
  }
```

**Comment by IxtiyorDeveloper** [comment]
same problem!

**Comment by stephanebelazouz** [comment]
+1

**Comment by mnmonherdene1234** [comment]
![image](https://github.com/user-attachments/assets/27830b8d-06f8-4ad3-86ce-917add245059)

"next": "15.0.3"
"antd": "^5.22.1"
"react": "^18"

**Comment by LysenkovVA** [comment]
Same

"next": "15.0.3",
"antd": "^5.22.1",
"react": "^18.3.1",
"react-dom": "^18.3.1"

**Comment by xu756** [comment]
Same
```
 "@ant-design/nextjs-registry": "^1.0.2",
    "antd": "^5.22.1",
    "dayjs": "^1.11.13",
    "next": "15.0.3",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106"
```

**Comment by MahdiYazdan** [comment]
**Same Problem** 
`"@ant-design/nextjs-registry": "^1.0.2",
    "next": "15.0.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"`

**Comment by rftglyv** [comment]
@ant-design/nextjs-registry is updated to 1.0.2 and it's now compatible with NextJs 15 and React 19 but yet still AntD itself isn't :(

**Comment by beerkayaslan** [comment]
same problem

**Comment by vinicius-hayden** [comment]
Same here!

My issue is with the `OffCanvas` react-bootstrap component

``
 "bootstrap": "^5.3.3",
    "next": "^15.0.3",
    "react": "^18.3.1",
    "react-bootstrap": "^2.10.5",
    "react-dom": "^18.3.1",
``

**Comment by dgtllion** [comment]
i created some workaround for antd related issues.
Take a look here https://github.com/ant-design/ant-design/issues/51339

**Comment by 2u3j6** [comment]
> ### Reproduction link复制链接
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/ecd139ba9847d0c77607c86339eb8ee6939ca85143a92ae16ebf20f58325e1b6/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/p/sandbox/nice-danny-6h7ckz?file=%2Fsrc%2FApp.tsx%3A16%2C25)
> 
> ### Steps to reproduce重现步骤
> Add a children prop to a Menu item. No warning is given if the children prop is removed. No "ref" prop is needed for a warning to appear (if children prop is provided).将 Children 属性添加到菜单项。如果移除了 Children 支柱，则不会发出警告。不需要“ref”道具即可出现警告（如果提供了 Children 道具）。
> 
> ### What is expected?预期是什么？
> No warning should appear.不应出现任何警告。
> 
> ### What is actually happening?
> 到底发生了什么？
> Full warning is:完整的警告是：
> 
> Warning: Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.警告：React 19 中删除了对 element.ref 的访问。 ref 现在是常规 prop。它将在未来版本中从 JSX 元素类型中删除。
> 
> Environment	Info
> antd蚂蚁金服	5.18.05.18.0
> React反应	19.0.0-rc.019.0.0-rc.0
> System系统	Windows视窗
> Browser浏览器	Chrome v126.0.6468.2
> 浏览器 v126.0.6468.2

![image](https://github.com/user-attachments/assets/9994911e-b732-47ac-a1e5-1ae7ad41275d)
same with you 
how to fix

**Comment by dgtllion** [comment]
@2u3j6 you can look for my solution (patch nr 2) Wave.js.
And upgrade your antd to the 5.22.1

**Comment by Truimo** [comment]
Antd  ^5.21.6
NextJs 15.0.3
React 18.3.1

Have the same problem.

**Comment by vitalijalbu** [comment]
Same issue on mine, I think we need to wait all **rc-components** being updated.... 👀🚀

**Comment by vitalijalbu** [comment]
Same issue on mine, I think we need to wait all **rc-components** being updated.... 👀🚀

**Comment by palveeen22** [comment]
same problem, is there any solution folks?

**Comment by dgtllion** [comment]
> i created some workaround for antd related issues. Take a look here #51339

@palveeen22 you can use a workaround while antd is not compatible with react 19.

**Comment by vitalijalbu** [comment]
> > i created some workaround for antd related issues. Take a look here #51339
> 
> @palveeen22 you can use a workaround while antd is not compatible with react 19.

Yeah man that’s great, but too many components to edit… in my opinion , what stays inside node_modules shouldn’t be touched😁🤝
Let’s wait for @zombieJ team 🚀

**Comment by Chukwu3meka** [comment]
> > Same with Button component
> > ```
> > "@ant-design/nextjs-registry": "^1.0.1",
> > "antd": "^5.21.6",
> > "next": "15.0.2",
> > "react": "19.0.0-rc-02c0e824-20241028",
> > "react-dom": "19.0.0-rc-02c0e824-20241028"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @follow-prince Why not publish the patch ?
> 
> just dm me i will give you

Just be careful with installing 3rd party libraries

**Comment by heyj78sd** [comment]
> > > Same with Button component
> > > ```
> > > "@ant-design/nextjs-registry": "^1.0.1",
> > > "antd": "^5.21.6",
> > > "next": "15.0.2",
> > > "react": "19.0.0-rc-02c0e824-20241028",
> > > "react-dom": "19.0.0-rc-02c0e824-20241028"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @follow-prince Why not publish the patch ?
> > 
> > 
> > just dm me i will give you
> 
> Just be careful with installing 3rd party libraries

Next.js 15 uses the latest React19 version, but antd does not support React19 yet. It plans to support 19 in the next major version, but it needs to wait for the official release of React19.

If you need to temporarily solve this problem, you can reduce Next to v14

**Comment by C-L-STARK** [comment]
![image](https://github.com/user-attachments/assets/2488876b-1599-45a7-a855-9a18769da8d9)
have a plan to upgrade ? @zombieJ

**Comment by C-L-STARK** [comment]
no - -, hard

**Comment by alexfilitaryn-awtg** [comment]
+1

**Comment by ianzone** [comment]
Now React 19 has been released

**Comment by Kekajan** [comment]
+1

**Comment by saifookhan** [comment]
+1

**Comment by lexmin0412** [comment]
Same Problem.

**Comment by minorcell** [comment]
https://zh-hans.react.dev/blog/2024/04/25/react-19

**Comment by verhovensky** [comment]
Same for me with 

```
  "dependencies": {
    "antd": "^5.22.4",
    "next": "15.1.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  }
  ```

**Comment by prohui** [comment]
Same Problem.

**Comment by Saqib7865-dev** [comment]
Same issue while using RangePicker from DatePicker.

**Comment by arvinxx** [comment]
5.22.6 should fix this

**Comment by manzaloros** [comment]
> 5.22.6 should have fixed this.

Just FYI. 5.22.6 does not fix this issue. I still get `ref` console warnings with the `Layout` component and React 19 with Ant Design.

**Comment by vylink** [comment]
@MahdiYazdan , just tried on 5.22.7.. Didn't work until removed node_modules and re-installed dependencies. Hope it helps.

**Comment by Amaranthusss** [comment]
@vylink same here but I had to delete / update my yarn.lock
