### ISSUE TITLE
Incorrect Timezone with Luxon DatePicker when manually typing a date

### ISSUE THREAD

**Issue by pfe-nazaries** [ant-design/ant-design#51301]
### Reproduction link

[https://github.com/pabloimrik17/ant-design-luxon-timezone-manual-data-fill](https://github.com/pabloimrik17/ant-design-luxon-timezone-manual-data-fill)

### Steps to reproduce

clone the repo

run pnpm install

run pnpm dev

On the first datepicker manually type 08:10

On the second datepicker set the time to 08:10 using the selector

### What is expected?

Both datimes should have the same timezone America/New_York which is the value i configured via Luxon Settings object

### What is actually happening?

The first datetime (manually typed) has the users timezone, the second one is using the timezone configured via Luxon Settings object

![image](https://github.com/user-attachments/assets/93073d43-fc46-41b2-9f1a-921e7e3ddb2a)

| Environment | Info |
| --- | --- |
| antd | 5.21.4 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Chrome 129.0.6668.101 |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/picker/pull/883

**Comment by pfe-nazaries** [comment]
@Wxh16144 I hope you had a great weekend.

The issue will be not fixed with that change maybe a video will ilustrate the problem better

![timezone-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/92726fef-ed4f-4166-acd2-2abe65c03b8e)

**Comment by pfe-nazaries** [comment]
@afc163  @Wxh16144 please reopen the issue. Is not related to the previous one that i opened. The only common thing is that is also related to timezone handling, but is not fixed with the change that the previous one was solved.

Check the GIF above and my github repo with the repro

**Comment by pfe-nazaries** [comment]
Please review my repo and the GIF the issue is still there. Please re open this issue
