### ISSUE TITLE
Ant Design Component Causing Error ReactRender Is Not A Function

### ISSUE THREAD

**Issue by daffafikri19** [ant-design/ant-design#52080]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9?file=%2Findex.html%3A11%2C34)

### Steps to reproduce
1. Create a new project using Next.js 15.
2. Install antd version 5.22.5.
3. Wrap root layout with <AntdRegistery>
4. Import the Button component from antd into the `page.tsx` file.
5. Use the Button component in that Page.
6. Run the application using `npm run dev`.

### What is expected?

When I click the button, the `onClick` function attached to the button should be executed without errors, and no TypeError or other issues should occur.

### What is actually happening?

When I use the button from antd (So far I only use the button), when I click on it, the TypeError error occurs: reactRender is not a function.

I've checked it works regardless of whether you use the client or the server. I am using extjs 15 and the latest version of antd. I also tried to create a new clean next project and try it there, but the error is the same.

| Environment | Info |
| --- | --- |
| antd | 5.22.5 |
| React | 19.0.0 |
| System | Nextjs 15 |
| Browser | Chrome:latest |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/51952

**Comment by realityaudiostudio** [comment]
Same issue on react js while working with AntDes components

**Comment by pxtrickb** [comment]
Issue is still there on 5.22.5. Pops up when clicking an AntD button.

**Comment by sahSahy** [comment]
yes when click happens
![image](https://github.com/user-attachments/assets/1fa7b27d-23b7-42f0-876d-0458be8ce7d1)

**Comment by CloverOS** [comment]
![image](https://github.com/user-attachments/assets/78dcd1c0-35e2-4e76-9145-275d9dce57ef)
+1
 "react": "^18",
 "antd": "^5.22.5",
  "next": "15.1.2",

**Comment by EvgenBolat** [comment]
has somebody find the solution?
"react": "^19.0.0",
"next": "15.0.4",
"antd": "^5.22.5",

**Comment by aman1998** [comment]
not solution?

**Comment by AlizaKhan3** [comment]
Facing the same issue on clicking AntDesign button i'm having error which is; 
TypeError: reactRender is not a function

**Comment by andrei10k** [comment]
Same thing. Antd is not currently supporting react 19

**Comment by andrei10k** [comment]
i see its closed but its still not fixed. at least for modal.confirm its still throwing the same error in 5.22.6

**Comment by afc163** [comment]
@andrei10k Please remove node_modules and all lock files, try reinstall node_module.

**Comment by sahSahy** [comment]
i installed   
"react": "^18.2.0",
"react-dom": "^18.2.0",
 "antd": "^5.17.2",
 
 it works

**Comment by andrei10k** [comment]
@afc163 i did. same problem with react 19

**Comment by kitety** [comment]
save error, i have aready delete node_modules and reinstall it. React version 19

**Comment by ALfLuisV** [comment]
antD can show some compatibility issues if u are using react ^19, so, first, check your react version in package.json, if your react version is 19, this command might help you:

first, you should run this script in your frontend package terminal: 

npm install --save-dev @ant-design/v5-patch-for-react-19

and then, you have to import the antd compatibility patch in your jsx archive, just like this:

import '@ant-design/v5-patch-for-react-19';

**Comment by jerry-f** [comment]
This problem is still present in the latest version, in next:15.03 ; react: 18.3.1 “antd-mobile”:“^5.38.1”, it still occurs when importing toash

**Comment by MMedeiros03** [comment]
For me it was resolved by returning to react ^ 18

**Comment by webjohnjiang** [comment]
i revert react version to 18 worked for me. By the way, remember revert react-dom too

**Comment by rpasechnikov** [comment]
I tried this (https://ant.design/docs/react/v5-for-19) workaround, however after installing the package and adding `import "@ant-design/v5-patch-for-react-19";` in either the root `layout.tsx` or directly in the target component, I started getting another error:

`Export unstableSetRender doesn't exist in target module`. It looks like this module is not present in the `antd` package. Any ideas?

Full error:
```
./node_modules/.pnpm/@ant-design+v5-patch-for-react-19@1.0.3_antd@5.22.5_react-dom@19.0.0_react@19.0.0__react@19.0_woot36jsp3wkv2wbpd2supzpya/node_modules/@ant-design/v5-patch-for-react-19/es/index.js:3:1
Export unstableSetRender doesn't exist in target module
  1 | 'use client';
  2 |
> 3 | import { unstableSetRender } from 'antd';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  4 | import { createRoot } from 'react-dom/client';
  5 | unstableSetRender(function (node, container) {
  6 |   container._reactRoot || (container._reactRoot = createRoot(container));

The export unstableSetRender was not found in module [project]/node_modules/.pnpm/antd@5.22.5_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/antd/es/index.js [app-client] (ecmascript) <exports>.
Did you mean to import Table?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.
```

**Comment by SValentyn** [comment]
Applying `@ant-design/v5-patch-for-react-19` – didn't help, the error didn't go away.
However, I was able to add a workaround by rendering the portal components as in the following code:

```ts
import { ReactElement, StrictMode } from 'react';
import { createRoot, Root } from 'react-dom/client';
import { unstableSetRender } from "antd/lib/config-provider/UnstableContext";
import App from './App';
import "./style/index.scss";

/**
 * Creates the main React root and targets the HTML element with the id="root".
 */
const root: Root = createRoot(document.getElementById('root') as HTMLElement);

/**
 * Renders the React application within the created root.
 */
root.render(
    <StrictMode>
        <App/>
    </StrictMode>
);

/**
 * Overrides the default patch of rendering behavior for antd's internal portal components.
 * IMPORTANT: Will be removed after adding React 19 support out-of-the-box.
 *
 * @param node - The React element that antd intends to render in a portal.
 * @param container - The DOM container or document fragment where the element should be rendered.
 * @returns A cleanup function that unmounts the root when the portal is removed.
 */
unstableSetRender((node: ReactElement, container: Element | DocumentFragment) => {
    // Render portal component
    const portalRoot: Root = createRoot(container);
    portalRoot.render(node);

    // Return a cleanup function that unmounts the portal
    return async () => {
        await new Promise((resolve) => setTimeout(resolve, 0));
        portalRoot.unmount();
    };
});

```

dependencies:
"react": "19.0.0",
"react-dom": "19.0.0",
"antd": "5.24.0",

P.S.  I definitely think the antd team (@afc163) needs to add a full-fledged example of using `unstableSetRender`, particularly for typescript projects.

**Comment by boas19910115** [comment]
呵呵

**Comment by ZiadAssem** [comment]
> I tried this (https://ant.design/docs/react/v5-for-19) workaround, however after installing the package and adding `import "@ant-design/v5-patch-for-react-19";` in either the root `layout.tsx` or directly in the target component, I started getting another error:
> 
> `Export unstableSetRender doesn't exist in target module`. It looks like this module is not present in the `antd` package. Any ideas?
> 
> Full error:
> 
> ```
> ./node_modules/.pnpm/@ant-design+v5-patch-for-react-19@1.0.3_antd@5.22.5_react-dom@19.0.0_react@19.0.0__react@19.0_woot36jsp3wkv2wbpd2supzpya/node_modules/@ant-design/v5-patch-for-react-19/es/index.js:3:1
> Export unstableSetRender doesn't exist in target module
>   1 | 'use client';
>   2 |
> > 3 | import { unstableSetRender } from 'antd';
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   4 | import { createRoot } from 'react-dom/client';
>   5 | unstableSetRender(function (node, container) {
>   6 |   container._reactRoot || (container._reactRoot = createRoot(container));
> 
> The export unstableSetRender was not found in module [project]/node_modules/.pnpm/antd@5.22.5_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/antd/es/index.js [app-client] (ecmascript) <exports>.
> Did you mean to import Table?
> All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.
> ```
> 
> **Update:** Make sure that you are on `"antd": "^5.23.1"` or above, since if you are below that, you will run into the same issue as me.

I'm on 5.23.3 and have a similar error:
`unhandledRejection TypeError: (0 , r.unstableSetRender) is not a function
    at 19614 (.next/server/chunks/693.js:1:125634)
    at o (.next/server/webpack-runtime.js:1:127)
    at <unknown> (.next/server/chunks/954.js:1:4357)
    at o.a (.next/server/webpack-runtime.js:1:866)
    at 7954 (.next/server/chunks/954.js:1:4292)
    at o (.next/server/webpack-runtime.js:1:127)
    at t (.next/server/pages/_app.js:1:3216)
    at <unknown> (.next/server/pages/_app.js:1:3251)
    at o.X (.next/server/webpack-runtime.js:1:1678)
    at <unknown> (.next/server/pages/_app.js:1:3229) {
  type: 'TypeError'
}`

**Comment by xsfxtsxxr** [comment]
> For me it was resolved by returning to react ^ 18

it's ok for me to change it to react@18
