### ISSUE TITLE
Select: height is not calculated correctly

### ISSUE THREAD

**Issue by Pareder** [ant-design/ant-design#55953]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/hopeful-sea-l72w5s)

### Steps to reproduce

1. override `controlHeight` and `fontSize` Select tokens in `ConfigProvider`
2. render `Select` component of different sizes

### What is expected?

Expected Select component to have the same height as provided in `controlHeight`.

### What is actually happening?

The height differs by the difference of provided `fontSize` Select token and global `fontSize` token multiplied by `lineHeight` value.

The thing is that vertical padding uses [global `fontHeight` token](https://github.com/ant-design/ant-design/blob/1b271fcafd3241dba0e1db785e41aca89a993dfd/components/theme/themes/shared/genFontMapToken.ts#L32) in calculation [https://github.com/ant-design/ant-design/blob/1b271fcafd3241dba0e1db785e41aca89a993dfd/components/select/style/select-input.ts#L111](https://github.com/ant-design/ant-design/blob/1b271fcafd3241dba0e1db785e41aca89a993dfd/components/select/style/select-input.ts#L111) but then content uses component overridden `fontSize` token [https://github.com/ant-design/ant-design/blob/1b271fcafd3241dba0e1db785e41aca89a993dfd/components/select/style/select-input.ts#L102](https://github.com/ant-design/ant-design/blob/1b271fcafd3241dba0e1db785e41aca89a993dfd/components/select/style/select-input.ts#L102) and it may differ from the global value.

One of the possible fix would be to calculate `fontHeight` on component level:
```
'--select-font-height': Math.round(token.lineHeight * token.fontSize)
```
And the same for `small` and `large` sizes.

| Environment | Info |
| --- | --- |
| antd | 6.0.0 |
| React | 18.3.1 |
| System | Windows 11 |
| Browser | Google Chrome 142.0.7444.176 |

---
It is possible to override `fontHeight` token on component level but:
1. it is not so obvious and straight-forward
2. it is not typed in TS:
    ```
    Object literal may only specify known properties, and 'fontHeight' does not exist in type 'Partial<ComponentToken> & Partial<AliasToken> & { algorithm?: boolean | MappingAlgorithm | MappingAlgorithm[] | undefined; }'.
    ```

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/57014

**Comment by Pareder** [comment]
@afc163 Actually it was not fixed, you can open reproduction link and compare the rendered height to `controlHeight` tokens.
