### ISSUE TITLE
getFieldDecorator and array value, e.g. Checkbox.Group

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#5957]
### Version
2.9.3

### Environment
osx, chrome

### Reproduction link
[http://codepen.io/anon/pen/VbpWNj?editors=0010](http://codepen.io/anon/pen/VbpWNj?editors=0010)

### Steps to reproduce
nothing special

### What is expected?
expects that **getFieldDecorator** will get value by self

### What is actually happening?
it works only for simple components,  e.g. **getFieldDecorator** and **Checkbox.Group** is not working as supposed

---
https://github.com/react-component/form/issues/73

**Comment by paranoidjk** [comment]
~~getFieldDecorator('user_options')~~ --> getFieldDecorator('options')

**Comment by grunmin** [comment]
```
<Form.Item label="">
{
    getFieldDecorator('action', {
    initialValue: ['login'],
    valuePropName: 'checked',
    rules: [{ type: 'array', required: true, message: '请至少选择一项' }]
    })(<CheckboxGroup options={actionOptions}  />)
}
</Form.Item>
```
![image](https://user-images.githubusercontent.com/4323398/34477887-5df86dd0-efd8-11e7-9135-cc4b753334d1.png)

问题就是: 指定了initialValue, 但是checkbox并没有勾选上.

**Comment by MAAARKIN** [comment]
@grunmin same problem here, you fix this problem?

**Comment by grunmin** [comment]
@MAAARKIN No

**Comment by afc163** [comment]
@grunmin @MAAARKIN Hey guys, `CheckboxGroup` don't have `checked` prop, you should not set `valuePropName: 'checked',`.

**Comment by MAAARKIN** [comment]
@grunmin i fixed my problem in Checkbox Group with options. the initialValue want a boolean value (idk why this behavior...).

@afc163 ok, same if u not set valuePropName, this code that @grunmin post, not work. I don't know why this behavior

try this code and i think that will be solve your problem.
```
const actionOptions = [
  {label: 'foo', value: 'save'},
  {label: 'bar', value: 'login'},
]

const selectedOptions = [
  {label: 'bar', value: 'login'}
]
<Form.Item label="">
{
    getFieldDecorator('action', {
    initialValue: selectedOptions.map( opt => opt && opt.value ),
    rules: [{ type: 'array', required: true, message: 'your message' }]
    })(<CheckboxGroup options={actionOptions}  />)
}
</Form.Item>
```

One more, if you using mapPropsToFields and setting value in createFormField the initialValue will not work.

**Comment by thg303** [comment]
is there any solution for Select and Options?

**Comment by tarun4all** [comment]
how to get the value of selected checkbox in antd form ?? i am still not able to find the answers.

**Comment by Dibyn7** [comment]
@tarun4all 
const actionOptions = [
  {label: 'foo', value: 'save'},
  {label: 'bar', value: 'login'},
]

const selectedOptions = [
  {label: 'bar', value: 'login'}
]
<Form.Item label="">
{
    getFieldDecorator('action', {
    initialValue: selectedOptions.map( opt => opt && opt.value ),
    rules: [{ type: 'array', required: true, message: 'your message' }],
    _valuePropName: 'value'_
    })(<CheckboxGroup _onChange={value => selected.push({ label: 'Your_label', value })}_ _value={selectedOptions.map( opt => opt && opt.value )}_  options={actionOptions}  />)
}
</Form.Item>
This will solve most the issue like initial Value, default checking but if you want to no default checking, set _value_ to empty array. 
Thanks. I hope I am doing it the right way but this is how I fixed the issue.
