### ISSUE TITLE
Table with fixed columns display error

### ISSUE THREAD

**Issue by joshbenhamou** [ant-design/ant-design#7605]
### Version
2.13.1

### Environment
Mac OS, Chrome, React 15.6

### Reproduction link
[https://codepen.io/joshbenhamou/pen/mBJJdQ](https://codepen.io/joshbenhamou/pen/mBJJdQ)

### Steps to reproduce
Having fixed columns left and right with data shows a double display of the fixed right column if there are not enough columns to cover the entire screen. Appears to only be when defining widths for all columns

### What is expected?
The fixed column on the right should stretch across the remaining screen

### What is actually happening?
Double-display of fixed column

**Comment by afc163** [comment]
Try reinstall node_modules. It was fixed in https://github.com/react-component/table/commit/abade807bab08d17396a7df8fe5b741a7f1cb847

**Comment by joshbenhamou** [comment]
No change after reinstalling node_modules. Also the issue you've referenced doesn't seem to mention the above?

**Comment by joshbenhamou** [comment]
Ah this isn't on 2.13.1, will wait for this to be on the next version, thanks

**Comment by afc163** [comment]
My mistake, that is a different issue.

You have to define widths for all fixed columns, and make sure scroll.x larger than the rest of columns.

**Comment by joshbenhamou** [comment]
Still happening for me even when setting the scroll.x to be greater than the widths:
```
scroll={{
              y: tableHeight,
              x: _.sum(_.map(grid.columns, 'width')) + 1
            }}
```

Also check out the codepen, the widths total 1350 whereas the scroll.x is 1500

**Comment by joshbenhamou** [comment]
`A fixed value which is greater than table width for scroll.x is recommended. The sum of unfixed columns should not greater than scroll.x.`

If this a misunderstanding issue, then the above line in the documentation confused me. In the codepen example provided, what should I be setting as the scroll.x?

I've tried a few variations of setting the width on fixed/not fixed & updating the scroll.x but no luck

**Comment by afc163** [comment]
I fixed the expression which is a little misleading.

---

> The width unfixed columns is 1350 and the scroll.x is 1500

Don't fixed width for every unfixed columns, you can leave one column to be flexible.

https://codepen.io/anon/pen/EwVmGo

**Comment by joshbenhamou** [comment]
So if all widths are set (including fixed columns) what should scroll.x be because even with 1350, the bug still shows?

**Comment by joshbenhamou** [comment]
See https://codepen.io/joshbenhamou/pen/mBJJdQ

**Comment by joshbenhamou** [comment]
Replying to the edit above, this doesn't work when there are more columns that can be fit on screen, see - https://codepen.io/joshbenhamou/pen/mBJJdQ
