### ISSUE TITLE
Layout Content not correct render on server side render

### ISSUE THREAD

**Issue by cstur** [ant-design/ant-design#8604]
### Version
3.0.1

### Environment
mac chrome latest

### Reproduction link
[https://github.com/cstur/next-with-antd](https://github.com/cstur/next-with-antd)

### Steps to reproduce
Refresh Page，Content are render under sider bar, please  see screenshot
[screenshot](https://github.com/cstur/next-with-antd/blob/master/%E9%94%99%E8%AF%AF%E6%88%AA%E5%9B%BE.png)

### What is expected?
content correct render

### What is actually happening?
content not correct render

---
this issue happens antd version >2.13.9

**Comment by yesmeck** [comment]
Works on my mac, could you confirm does this issue has been fixed?

**Comment by cstur** [comment]
I tried antd3.0.2 the issue still exist, the content is render under sider bar on first load then jump up

**Comment by yesmeck** [comment]
Hmm, looks like same issue as https://github.com/ant-design/ant-design/issues/8612

**Comment by cstur** [comment]
this.state.siders.length > 0 always false on SSR may cause this issue 
```
// ant-design/components/layout/layout.tsx line 63
...
      [`${prefixCls}-has-sider`]: this.state.siders.length > 0,
...
```

**Comment by yesmeck** [comment]
Your are right, `componentDidMount` never been called on server side.

https://github.com/ant-design/ant-design/blob/13c6e8ec1e4afb244f78a64ad2b956cf388d2bd5/components/layout/Sider.tsx#L136

**Comment by Shadowman4205** [comment]
is hasSider wil be available on master?

**Comment by mitjade** [comment]
I too would like to know when this could be released?

**Comment by yesmeck** [comment]
This weekend.

**Comment by tim-soft** [comment]
Can confirm latest version fixes the issue, thanks guys!

**Comment by ukyiwin** [comment]
I can't resolve with latest version 
![Screenshot from 2019-04-06 13-38-39](https://user-images.githubusercontent.com/35300439/55666219-6032c700-5871-11e9-81c9-746dfe83c9ca.png)
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-less": "^1.0.1",
    "antd": "^3.16.2-alpha.0",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-styled-components": "^1.10.0",
    "classnames": "^2.2.6",
    "dotenv-webpack": "^1.7.0",
    "express": "^4.16.4",
    "less": "^3.9.0",
    "less-vars-to-js": "^1.3.0",
    "next": "^8.0.4",
    "rc-animate": "^2.6.0",
    "react": "^16.8.6",
    "react-container-query": "^0.11.0",
    "react-dom": "^16.8.6",
    "react-media": "^1.9.2",
    "styled-components": "^4.2.0"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.10.0"
  }

**Comment by ckwun** [comment]
> @tim-soft
> still issue!
> ![Screenshot from 2019-04-06 13-38-39](https://user-images.githubusercontent.com/35300439/55666219-6032c700-5871-11e9-81c9-746dfe83c9ca.png)
> "dependencies": {
> "@zeit/next-css": "^1.0.1",
> "@zeit/next-less": "^1.0.1",
> "antd": "^3.16.2-alpha.0",
> "babel-plugin-import": "^1.11.0",
> "babel-plugin-styled-components": "^1.10.0",
> "classnames": "^2.2.6",
> "dotenv-webpack": "^1.7.0",
> "express": "^4.16.4",
> "less": "^3.9.0",
> "less-vars-to-js": "^1.3.0",
> "next": "^8.0.4",
> "rc-animate": "^2.6.0",
> "react": "^16.8.6",
> "react-container-query": "^0.11.0",
> "react-dom": "^16.8.6",
> "react-media": "^1.9.2",
> "styled-components": "^4.2.0"
> },
> "devDependencies": {
> "babel-plugin-styled-components": "^1.10.0"
> }

You need to add the prop hasSider to the <Layout> you use. i.e. <Layout hasSider={true|false}> and it should works
