### ISSUE TITLE
react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none was installed

### ISSUE THREAD

**Issue by techird** [ant-design/ant-design#8625]
### Version
3.0.1

### Environment
node

### Reproduction link
[https://codesandbox.io/s/k278o43m0v](https://codesandbox.io/s/k278o43m0v)

### Steps to reproduce
just run `npm install antd`

### What is expected?
package installed without warnings.

### What is actually happening?
package installed with warnings:

```
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none was installed.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none was installed.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none was installed.
```

---
I use react 16, so the peer dependency do not match. [react-slick](https://github.com/akiran/react-slick) seem to fix this via this [PR](https://github.com/akiran/react-slick/pull/866), yet not published to npm with version [0.15.4](http://registry.npmjs.org/react-slick/0.15.4). Upgrade to [0.16.0](http://registry.npmjs.org/react-slick/0.16.0) may fix this.

By the way, is `jquery` required for the new component `slick-carousel`? That's not nice.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/d7dcb56dfcea01ed500bc1ce0d8e154f6dba178e

**Comment by chenpeng1102** [comment]
@afc163 I replace ant-design 3.x to ant-design#master, `yarn check` still have some error cased by ant-design

> error "antd#rc-editor-mention#immutable@~3.7.4" doesn't satisfy found match of "immutable@3.8.2"

**Comment by megawac** [comment]
☝️ fixed by https://github.com/react-component/editor-mention/pull/27
