### ISSUE TITLE
fixed table on the left and right can't response to table head of main content

### ISSUE THREAD

**Issue by SteveJob** [ant-design/ant-design#9230]
### Version
3.1.6

### Environment
Mac OSX 10.13.2/chrome 63、Windows/chrome

### Reproduction link
[https://8yw2m7rmol.codesandbox.io/](https://8yw2m7rmol.codesandbox.io/)

### Steps to reproduce
1. use grouping table head
2. fix some column on the left or right

### What is expected?
align content to the rows

### What is actually happening?
fixed column is unaligned
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fo1xhxapuhj31kw0tb7cb.jpg)

**Comment by simondiep** [comment]
I've noticed the same issue when you specify column widths.

https://codesandbox.io/s/m7o5zj1j3y

If you increase the browser width, an unexpected column appears next to the fixed left column.

**Comment by yesmeck** [comment]
Fixed in rc-table@6.1.5

**Comment by simondiep** [comment]
This still appears to be an issue.  The above links are referencing the latest AntD with 6.1.x rc-table and you can still see a gap between the first and second columns.

**Comment by yesmeck** [comment]
Leave one column's width to blank.
